"""
Additional Missing Features — Sections AN-AX
============================================
"""

from dataclasses import dataclass, field
from typing import List
from enum import Enum, auto


class AdditionalSystem(Enum):
    DIPLOMATIC_EXTENDED = auto()
    INTELLIGENCE_SYSTEM = auto()
    PROPAGANDA_SYSTEM = auto()
    TRADE_SYSTEM = auto()
    CURRENCY_SYSTEM = auto()
    LABOR_SYSTEM = auto()
    HOUSING_SYSTEM = auto()
    MEDICINE_EXTENDED = auto()
    MUSIC_SYSTEM = auto()
    SMELL_SYSTEM = auto()
    ARCHITECTURAL_EXTENDED = auto()


@dataclass
class AdditionalFeature:
    feature_id: str
    feature_name: str
    system: AdditionalSystem
    normal_range: tuple
    unit: str
    description: str
    measurement: str
    tags: List[str] = field(default_factory=list)


ADDITIONAL_FEATURES: dict = {}


def _register_additional_features():
    global ADDITIONAL_FEATURES
    
    features = [
        # ============ AN: DIPLOMATIC & INTERNATIONAL (25 features) ============
        AdditionalFeature("dip.treaty_ratification", "Treaty Ratification Process", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 12), "months", "Signature, ratification, accession, entry into force",
                          "Legal"),
        AdditionalFeature("dip.reservation_clause", "Reservation Clause", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Partial acceptance - compatibility with object and purpose",
                          "Treaty"),
        AdditionalFeature("dip.mfn_status", "Most Favored Nation Status", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Non-discrimination - GATT Article I",
                          "Trade"),
        AdditionalFeature("dip.national_treatment", "National Treatment", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Foreign = domestic once inside - GATT Article III",
                          "Trade"),
        AdditionalFeature("dip.tariff_binding", "Tariff Binding", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 500), "%", "Maximum rate commitment - WTO schedule",
                          "WTO"),
        AdditionalFeature("dip.dispute_panel", "Dispute Settlement Panel", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "WTO adjudication - retaliation authorization",
                          "WTO"),
        AdditionalFeature("dip.soft_law", "Soft Law Instrument", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Declaration, guideline - non-binding but influential",
                          "International"),
        AdditionalFeature("dip.treaty_interpretation", "Treaty Interpretation", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 3), "method", "VCLT rules - text, context, object and purpose",
                          "Legal"),
        AdditionalFeature("dip.rebus_sic_stantibus", "Rebus Sic Stantibus", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Fundamental change of circumstances - termination ground",
                          "Legal"),
        AdditionalFeature("dip.jus_cogens", "Jus Cogens", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 10), "norms", "Peremptory norm - no derogation permitted (torture, genocide)",
                          "Legal"),
        AdditionalFeature("dip.erga_omnes", "Erga Omnes Obligation", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Owed to all - standing for non-injured states",
                          "Legal"),
        AdditionalFeature("dip.diplomatic_immunity", "Diplomatic Immunity", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Persona non grata - inviolability of premises",
                          "Vienna"),
        AdditionalFeature("dip.consular_protection", "Consular Protection", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Assistance to nationals abroad - Vienna Convention",
                          "Consular"),
        AdditionalFeature("dip.asylum_grant", "Asylum Grant", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 2), "type", "Territorial vs. diplomatic - Julian Assange embassy",
                          "Asylum"),
        AdditionalFeature("dip.extradition_treaty", "Extradition Treaty", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Dual criminality requirement - political offense exception",
                          "Treaty"),
        AdditionalFeature("dip.immigration_visa", "Immigration Visa", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 10), "type", "Tourist, work, student, immigrant - requirements",
                          "Immigration"),
        AdditionalFeature("dip.work_permit", "Work Permit", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Employment authorization for foreigners",
                          "Labor"),
        AdditionalFeature("dip.student_visa", "Student Visa", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "F-1, M-1, J-1 - study permits",
                          "Immigration"),
        AdditionalFeature("dip.permanent_residence", "Permanent Residence", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Green card or equivalent - path to citizenship",
                          "Immigration"),
        AdditionalFeature("dip.citizenship_naturalization", "Citizenship Naturalization", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 10), "years", "Residency requirement - good character",
                          "Naturalization"),
        AdditionalFeature("dip.dual_citizenship", "Dual Citizenship", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Allowed or prohibited - multiple nationalities",
                          "Law"),
        AdditionalFeature("dip.deportation", "Deportation", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Removal from country - grounds",
                          "Immigration"),
        AdditionalFeature("dip.asylum_seeker", "Asylum Seeker Status", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1), "scale", "Refugee claim pending - work authorization",
                          "Asylum"),
        AdditionalFeature("dip.migration_flow", "Migration Flow", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 1000000), "people/year", "Net migration - push/pull factors",
                          "Data"),
        AdditionalFeature("dip.diaspora", "Diaspora Population", AdditionalSystem.DIPLOMATIC_EXTENDED,
                          (0, 10000000), "people", "Expatriates living abroad",
                          "Census"),


        # ============ AO: INTELLIGENCE & ESPIONAGE (25 features) ============
        AdditionalFeature("int.humint", "Human Intelligence (HUMINT)", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Agent recruitment - MICE (money, ideology, compromise, ego)",
                          "Operations"),
        AdditionalFeature("int.sigint", "Signals Intelligence (SIGINT)", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Intercept and cryptanalysis - Enigma, Venona",
                          "Collection"),
        AdditionalFeature("int.imint", "Imagery Intelligence (IMINT)", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Satellite and aerial photography - resolution limits",
                          "Collection"),
        AdditionalFeature("int.masint", "Measurement and Signature (MASINT)", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Radar, acoustic, nuclear - technical data",
                          "Collection"),
        AdditionalFeature("int.osint", "Open Source Intelligence (OSINT)", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Publicly available information - social media mining",
                          "Collection"),
        AdditionalFeature("int.cover_identity", "Cover Identity Construction", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Legend building - consistency and backstop",
                          "Tradecraft"),
        AdditionalFeature("int.dead_drop", "Dead Drop Technique", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Non-meeting exchange - signal site and cache",
                          "Tradecraft"),
        AdditionalFeature("int.brush_pass", "Brush Pass", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Brief physical exchange - surveillance evasion",
                          "Tradecraft"),
        AdditionalFeature("int.sdr", "Surveillance Detection Route", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "SDR - identifying if followed",
                          "Tradecraft"),
        AdditionalFeature("int.compartmentalization", "Tradecraft Compartmentalization", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Need-to-know - cell structure",
                          "Security"),
        AdditionalFeature("int.double_agent", "Double Agent Management", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Feeding disinformation - trust but verify",
                          "Operations"),
        AdditionalFeature("int.mole_hunt", "Mole Hunt", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Counter-intelligence - suspicion and paranoia",
                          "CI"),
        AdditionalFeature("int.polygraph", "Polygraph Reliability", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (70, 90), "%", "70-90% accuracy - false positive problem",
                          "Testing"),
        AdditionalFeature("int.enhanced_interrogation", "Enhanced Interrogation", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Torture efficacy - Senate Intelligence report",
                          "Controversial"),
        AdditionalFeature("int.assassination", "Assassination by Poison", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Polonium-210, Novichok - attribution and deniability",
                          "Targeting"),
        AdditionalFeature("int.signal_interest", "Signal of Interest", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 100), "indicators", "Behaviors warranting attention",
                          "Analysis"),
        AdditionalFeature("int.coverage_gap", "Coverage Gap", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Intelligence failure - missed warning",
                          "Analysis"),
        AdditionalFeature("int.counter_intelligence", "Counter-Intelligence", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Protective intelligence - threat assessment",
                          "CI"),
        AdditionalFeature("int.intel_sharing", "Intelligence Sharing", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Five Eyes, NATO -盟友 relationships",
                          "Cooperation"),
        AdditionalFeature("int.source_network", "Source Network", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 100), "agents", "Web of human sources",
                          "Operations"),
        AdditionalFeature("int.analytic_Tradecraft", "Analytic Tradecraft", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 10), "standards", "Structured analytic techniques",
                          "Analysis"),
        AdditionalFeature("int.intel_bureaucracy", "Intelligence Bureaucracy", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 10), "agencies", "CIA, NSA, MI6, Mossad - coordination",
                          "Structure"),
        AdditionalFeature("int.collection_architecture", "Collection Architecture", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 1), "scale", "Tasking and collection management",
                          "Operations"),
        AdditionalFeature("int.production_cycle", "Production Cycle", AdditionalSystem.INTELLIGENCE_SYSTEM,
                          (0, 30), "days", "From raw intel to finished product",
                          "Timeliness"),


        # ============ AP: PROPAGANDA & PSYCHOLOGICAL WARFARE (25 features) ============
        AdditionalFeature("prop.agitprop", "Agitprop Design", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Agitation + propaganda - poster and film",
                          "Creative"),
        AdditionalFeature("prop.big_lie", "Big Lie Technique", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "So colossal no one believes it fabricated - Goebbels",
                          "Technique"),
        AdditionalFeature("prop.firehose", "Firehose of Falsehood", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "High volume, multiple channels, no consistency - Russian model",
                          "Technique"),
        AdditionalFeature("prop.active_measures", "Active Measures", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Subversion and disinformation - KGB tradition",
                          "Operations"),
        AdditionalFeature("prop.computational_propaganda", "Computational Propaganda", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Bot networks - amplification and harassment",
                          "Digital"),
        AdditionalFeature("prop.deepfake", "Deepfake Deployment", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Synthetic video - political sabotage",
                          "Technology"),
        AdditionalFeature("prop.astroturf", "Astroturf Campaign", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Fake grassroots - corporate or state funded",
                          "Technique"),
        AdditionalFeature("prop.dog_whistle", "Dog Whistle Politics", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Coded language - plausible deniability",
                          "Technique"),
        AdditionalFeature("prop.fear_appeal", "Fear Appeal", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Threat + efficacy - protection motivation theory",
                          "Psychology"),
        AdditionalFeature("prop.bandwagon", "Bandwagon Effect", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Everyone is doing it - social proof",
                          "Technique"),
        AdditionalFeature("prop.glittering_generality", "Glittering Generality", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Virtue words - freedom, progress",
                          "Technique"),
        AdditionalFeature("prop.name_calling", "Name-Calling", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Dehumanization - vermin, cockroaches",
                          "Technique"),
        AdditionalFeature("prop.transfer", "Transfer Technique", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Symbol association - flag, cross, swastika",
                          "Technique"),
        AdditionalFeature("prop.testimonial", "Testimonial", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Celebrity or authority endorsement - credibility borrowing",
                          "Technique"),
        AdditionalFeature("prop.plain_folks", "Plain Folks Appeal", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "I am just like you - elite camouflage",
                          "Technique"),
        AdditionalFeature("prop.framing", "Framing", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "How information is presented - emphasis",
                          "Cognitive"),
        AdditionalFeature("prop.narrative", "Narrative Construction", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Story creation for influence",
                          "Content"),
        AdditionalFeature("prop.memetics", "Memetics", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Viral idea propagation",
                          "Theory"),
        AdditionalFeature("prop.disinformation", "Disinformation", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "False information deliberately spread",
                          "Operations"),
        AdditionalFeature("prop.misinformation", "Misinformation", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "False information without intent",
                          "Spread"),
        AdditionalFeature("prop.fact_check_accuracy", "Fact-Check Accuracy", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 100), "%", "Verification organizations accuracy",
                          "Fact-checking"),
        AdditionalFeature("prop.media_literacy", "Media Literacy", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 100), "score", "Public ability to detect propaganda",
                          "Assessment"),
        AdditionalFeature("prop.confirmation_bias", "Confirmation Bias", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Seeking info that confirms beliefs",
                          "Psychology"),
        AdditionalFeature("prop.filter_bubble", "Filter Bubble", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Algorithmic isolation from opposing views",
                          "Algorithms"),
        AdditionalFeature("prop.echo_chamber", "Echo Chamber", AdditionalSystem.PROPAGANDA_SYSTEM,
                          (0, 1), "scale", "Reinforcement within like-minded groups",
                          "Social"),


        # ============ AQ: TRADE & COMMERCE (25 features) ============
        AdditionalFeature("trade.lc_types", "Letter of Credit Types", AdditionalSystem.TRADE_SYSTEM,
                          (0, 5), "type", "Revocable, irrevocable, confirmed, transferable",
                          "Finance"),
        AdditionalFeature("trade.documentary_collection", "Documentary Collection", AdditionalSystem.TRADE_SYSTEM,
                          (0, 2), "type", "D/P documents against payment, D/A acceptance",
                          "Finance"),
        AdditionalFeature("trade.open_account", "Open Account Terms", AdditionalSystem.TRADE_SYSTEM,
                          (0, 90), "days", "Ship now, pay later - trust and relationship",
                          "Finance"),
        AdditionalFeature("trade.consignment", "Consignment Arrangement", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Pay when sold - risk with supplier",
                          "Trade"),
        AdditionalFeature("trade.countertrade", "Countertrade", AdditionalSystem.TRADE_SYSTEM,
                          (0, 3), "type", "Barter, buyback, offset - hard currency shortage",
                          "Trade"),
        AdditionalFeature("trade.barter_exchange", "Barter Exchange Rate", AdditionalSystem.TRADE_SYSTEM,
                          (0, 100), "ratio", "1 cow = 5 sheep - negotiation and tradition",
                          "Trade"),
        AdditionalFeature("trade.market_day", "Market Day Cycle", AdditionalSystem.TRADE_SYSTEM,
                          (0, 7), "days", "Weekly rhythm - information aggregation",
                          "Markets"),
        AdditionalFeature("trade.fair_price", "Fair Price Concept", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Just price - scholastic economics",
                          "Philosophy"),
        AdditionalFeature("trade.usury", "Usury Prohibition", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Interest forbidden - workaround innovations",
                          "Religious"),
        AdditionalFeature("trade.commenda", "Commenda Contract", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Investor + traveling merchant - profit sharing, loss limited",
                          "Medieval"),
        AdditionalFeature("trade.joint_stock", "Joint Stock Company", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Shared ownership - risk pooling, capital aggregation",
                          "Finance"),
        AdditionalFeature("trade.limited_liability", "Limited Liability", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Investor loss capped - entrepreneurship incentive",
                          "Legal"),
        AdditionalFeature("trade.double_entry", "Double Entry Bookkeeping", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Debits and credits - error detection, capital tracking",
                          "Accounting"),
        AdditionalFeature("trade.bill_exchange", "Bill of Exchange", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Payment order - negotiable, discountable",
                          "Finance"),
        AdditionalFeature("trade.promissory_note", "Promissory Note", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "IOU - enforceable debt instrument",
                          "Finance"),
        AdditionalFeature("trade.fob_cif", "FOB vs CIF", AdditionalSystem.TRADE_SYSTEM,
                          (0, 2), "type", "Free on board vs cost insurance freight",
                          "Incoterms"),
        AdditionalFeature("trade.incoterms", "Incoterms", AdditionalSystem.TRADE_SYSTEM,
                          (0, 11), "terms", "Standard trade terms - EXW, FOB, CIF, DDP",
                          "Trade"),
        AdditionalFeature("trade.trade_credit_risk", "Trade Credit Risk", AdditionalSystem.TRADE_SYSTEM,
                          (0, 100), "%", "Probability of non-payment",
                          "Risk"),
        AdditionalFeature("trade.factoring", "Factoring", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Receivable selling - cash flow",
                          "Finance"),
        AdditionalFeature("trade.forfaiting", "Forfaiting", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Medium-term receivables - no recourse",
                          "Finance"),
        AdditionalFeature("trade.bank_guarantee", "Bank Guarantee", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Payment guarantee - performance bond",
                          "Finance"),
        AdditionalFeature("trade.standby_lc", "Standby LC", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Payment guarantee - secondary obligation",
                          "Finance"),
        AdditionalFeature("trade.trade_finance_volume", "Trade Finance Volume", AdditionalSystem.TRADE_SYSTEM,
                          (0, 10000000000), "USD", "Global trade finance market size",
                          "Market"),
        AdditionalFeature("trade.arbitration_clause", "Arbitration Clause", AdditionalSystem.TRADE_SYSTEM,
                          (0, 1), "scale", "Dispute resolution in contracts",
                          "Legal"),
        AdditionalFeature("trade.jurisdiction", "Choice of Jurisdiction", AdditionalSystem.TRADE_SYSTEM,
                          (0, 200), "countries", "Where disputes resolved",
                          "Legal"),


        # ============ AR: CURRENCY & MONETARY (25 features) ============
        AdditionalFeature("curr.commodity_money", "Commodity Money", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 10), "type", "Gold, silver, salt, cowrie shells - intrinsic value",
                          "History"),
        AdditionalFeature("curr.representative_money", "Representative Money", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Gold certificate - redeemable for commodity",
                          "History"),
        AdditionalFeature("curr.fiat_money", "Fiat Money", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Government decree - trust-based, no intrinsic value",
                          "Current"),
        AdditionalFeature("curr.banknote_issuance", "Banknote Issuance", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Private banks historically - central bank monopoly now",
                          "History"),
        AdditionalFeature("curr.coinage_debasement", "Coinage Debasement", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 100), "%", "Reduce precious metal content - inflation",
                          "History"),
        AdditionalFeature("curr.free_minting", "Free Minting", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Bring metal, get coins - price-specie flow mechanism",
                          "History"),
        AdditionalFeature("curr.gresham_law", "Gresham's Law", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Bad money drives out good - fixed exchange rate",
                          "Theory"),
        AdditionalFeature("curr.thiers_law", "Thiers' Law", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Good money drives out bad - floating exchange rate",
                          "Theory"),
        AdditionalFeature("curr.quantity_theory", "Quantity Theory of Money", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "MV = PY - inflation if M grows faster than Y",
                          "Theory"),
        AdditionalFeature("curr.seigniorage", "Seigniorage Revenue", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 10000000000), "currency", "Profit from minting - government income source",
                          "Finance"),
        AdditionalFeature("curr.currency_board", "Currency Board", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Domestic currency backed 100% by foreign reserve - Hong Kong",
                          "Arrangement"),
        AdditionalFeature("curr.dollarization", "Dollarization", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Adopt foreign currency - lose monetary sovereignty",
                          "Policy"),
        AdditionalFeature("curr.cryptocurrency_vol", "Cryptocurrency Volatility", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 100), "%", "Bitcoin price swings - store of value debate",
                          "Crypto"),
        AdditionalFeature("curr.stablecoin_peg", "Stablecoin Peg", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "Tether, USDC - reserve backing and redemption",
                          "Crypto"),
        AdditionalFeature("curr.cbdc", "Central Bank Digital Currency", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "scale", "CBDC - surveillance and programmability",
                          "Digital"),
        AdditionalFeature("curr.currency_in_circulation", "Currency in Circulation", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 100000000000), "units", "Cash outstanding",
                          "Data"),
        AdditionalFeature("curr.money_supply_m1", "Money Supply M1", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 10000000000), "currency", "Currency + demand deposits",
                          "Data"),
        AdditionalFeature("curr.money_supply_m2", "Money Supply M2", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 10000000000), "currency", "M1 + savings + time deposits",
                          "Data"),
        AdditionalFeature("curr.money_supply_m3", "Money Supply M3", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 10000000000), "currency", "M2 + large time deposits + institutional",
                          "Data"),
        AdditionalFeature("curr.velocity_money", "Velocity of Money", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 50), "turns", "Times per year money changes hands",
                          "Calculation"),
        AdditionalFeature("curr.reserves_ratio", "Reserves Ratio", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 100), "%", "Bank reserves to deposits - affects money multiplier",
                          "Banking"),
        AdditionalFeature("curr.interest_rate", "Interest Rate", AdditionalSystem.CURRENCY_SYSTEM,
                          (-5, 50), "%", "Cost of borrowing - monetary policy tool",
                          "Policy"),
        AdditionalFeature("curr.exchange_rate", "Exchange Rate", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 10000), "per USD", "Currency value against dollar",
                          "Market"),
        AdditionalFeature("curr.foreign_reserves", "Foreign Reserves", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 10000000000), "USD", "Central bank holdings - import coverage",
                          "Data"),
        AdditionalFeature("curr.gold_standard", "Gold Standard", AdditionalSystem.CURRENCY_SYSTEM,
                          (0, 1), "historical", "Currency tied to gold - ended 1971",
                          "History"),


        # ============ AS: LABOR & EMPLOYMENT (25 features) ============
        AdditionalFeature("labor.labor_participation", "Labor Force Participation Rate", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100), "%", "Working age employed or seeking - demographic shifts",
                          "BLS"),
        AdditionalFeature("labor.underemployment", "Underemployment Rate", AdditionalSystem.LABOR_SYSTEM,
                          (0, 30), "%", "Part-time wanting full-time, overqualified - hidden unemployment",
                          "BLS"),
        AdditionalFeature("labor.discouraged_worker", "Discouraged Worker Effect", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "Stopped looking - not counted in unemployment",
                          "BLS"),
        AdditionalFeature("labor.natural_unemployment", "Natural Rate of Unemployment", AdditionalSystem.LABOR_SYSTEM,
                          (0, 20), "%", "Frictional + structural - NAIRU concept",
                          "Economic"),
        AdditionalFeature("labor.phillips_curve", "Phillips Curve", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "Inflation-unemployment trade-off - flattened recently",
                          "Theory"),
        AdditionalFeature("labor.okuns_law", "Okun's Law", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "GDP growth and unemployment relationship - 2% growth ≈ 1% reduction",
                          "Economic"),
        AdditionalFeature("labor.beveridge_curve", "Beveridge Curve", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "Vacancies vs unemployment - mismatch indicator",
                          "BLS"),
        AdditionalFeature("labor.job_search_intensity", "Job Search Intensity", AdditionalSystem.LABOR_SYSTEM,
                          (0, 50), "applications/week", "Applications per week - unemployment duration",
                          "Survey"),
        AdditionalFeature("labor.reservation_wage", "Reservation Wage", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100000), "currency/year", "Minimum acceptable - declines with unemployment",
                          "Survey"),
        AdditionalFeature("labor.efficiency_wage", "Efficiency Wage", AdditionalSystem.LABOR_SYSTEM,
                          (0, 200), "%", "Above-market pay - reduces turnover and shirking",
                          "Theory"),
        AdditionalFeature("labor.minimum_wage", "Minimum Wage Effect", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "Employment reduction debate - monopsony model",
                          "Policy"),
        AdditionalFeature("labor.collective_bargaining", "Collective Bargaining Coverage", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100), "%", "Union contract percentage - wage compression",
                          "BLS"),
        AdditionalFeature("labor.strike_duration", "Strike Duration", AdditionalSystem.LABOR_SYSTEM,
                          (0, 365), "days", "Lost days - wage loss vs gain calculus",
                          "BLS"),
        AdditionalFeature("labor.lockout_tactic", "Lockout Tactic", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "Employer-initiated - pressure on union",
                          "Labor"),
        AdditionalFeature("labor.gig_classification", "Gig Economy Classification", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "Employee vs independent contractor - benefits and protections",
                          "Policy"),
        AdditionalFeature("labor.wage_gender_gap", "Wage Gender Gap", AdditionalSystem.LABOR_SYSTEM,
                          (0, 50), "%", "Earnings difference by gender",
                          "BLS"),
        AdditionalFeature("labor.wage_racial_gap", "Wage Racial Gap", AdditionalSystem.LABOR_SYSTEM,
                          (0, 50), "%", "Earnings difference by race",
                          "BLS"),
        AdditionalFeature("labor.union_density", "Union Density", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100), "%", "Union membership as percentage of workforce",
                          "BLS"),
        AdditionalFeature("labor.productivity", "Labor Productivity", AdditionalSystem.LABOR_SYSTEM,
                          (0, 10), "%/year", "Output per worker - growth driver",
                          "BLS"),
        AdditionalFeature("labor.automation_risk", "Automation Risk", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100), "%", "Job automation probability - Frey/Osborne categories",
                          "Studies"),
        AdditionalFeature("labor.remote_work", "Remote Work", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100), "%", "Work from home - post-pandemic",
                          "Survey"),
        AdditionalFeature("labor.fringe_benefits", "Fringe Benefits", AdditionalSystem.LABOR_SYSTEM,
                          (0, 50), "%", "Health, retirement, vacation as % of wages",
                          "BLS"),
        AdditionalFeature("labor.unemployment_duration", "Unemployment Duration", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100), "weeks", "Average weeks unemployed",
                          "BLS"),
        AdditionalFeature("labor.automation_tech", "Automation Technology Adoption", AdditionalSystem.LABOR_SYSTEM,
                          (0, 1), "scale", "Robotics and AI in workplace",
                          "Survey"),
        AdditionalFeature("labor.workforce_training", "Workforce Training", AdditionalSystem.LABOR_SYSTEM,
                          (0, 100), "hours/year", "Employer-provided training",
                          "Survey"),


        # ============ AT: HOUSING & REAL ESTATE (25 features) ============
        AdditionalFeature("housing.tenure_type", "Housing Tenure Type", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 4), "type", "Owner-occupied, rental, squatting, institutional",
                          "Census"),
        AdditionalFeature("housing.mortgage_amortization", "Mortgage Amortization", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 30), "years", "Fixed vs adjustable rate - term 15-30 years",
                          "Finance"),
        AdditionalFeature("housing.ltv_ratio", "Loan-to-Value Ratio", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 125), "%", "Down payment size - default risk and PMI",
                          "Underwriting"),
        AdditionalFeature("housing.dti_ratio", "Debt-to-Income Ratio", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 100), "%", "28/36 rule - lending standard",
                          "Underwriting"),
        AdditionalFeature("housing.bubble_indicator", "Housing Bubble Indicator", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 50), "ratio", "Price-to-income, price-to-rent - deviation from trend",
                          "Analysis"),
        AdditionalFeature("housing.foreclosure_process", "Foreclosure Process", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 3), "type", "Judicial vs non-judicial - timeline and deficiency judgment",
                          "Legal"),
        AdditionalFeature("housing.rent_control", "Rent Control Effect", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "Below-market rent - supply reduction and misallocation",
                          "Policy"),
        AdditionalFeature("housing.gentrification", "Gentrification Displacement", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "Wealthy in, poor out - cultural and economic",
                          "Study"),
        AdditionalFeature("housing.slum_formation", "Slum Formation", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "Informal settlement - infrastructure deficit",
                          "UN-Habitat"),
        AdditionalFeature("housing.homelessness_count", "Homelessness Count", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1000000), "people", "Point-in-time - chronic vs situational",
                          "HUD"),
        AdditionalFeature("housing.housing_first", "Housing First Model", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "Provide housing then services - evidence-based",
                          "Policy"),
        AdditionalFeature("housing.building_code", "Building Code Compliance", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "Safety standard - cost and enforcement",
                          "Building"),
        AdditionalFeature("housing.zoning_variance", "Zoning Variance", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "Exception to rules - political influence",
                          "Zoning"),
        AdditionalFeature("housing.eminent_domain", "Eminent Domain", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "Public taking - just compensation and blight definition",
                          "Legal"),
        AdditionalFeature("housing.property_tax", "Property Tax Assessment", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 10000000), "value", "Market value - Proposition 13 California distortion",
                          "Assessment"),
        AdditionalFeature("housing.homeownership_rate", "Homeownership Rate", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 100), "%", "Owner-occupied as % of households",
                          "Census"),
        AdditionalFeature("housing.median_rent", "Median Rent", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 10000), "currency/month", "Market rent for standard unit",
                          "Zillow"),
        AdditionalFeature("housing.median_home_price", "Median Home Price", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 10000000), "currency", "Typical home price",
                          "NAR"),
        AdditionalFeature("housing.housing_supply", "Housing Supply", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 10000000), "units", "Total housing stock",
                          "Census"),
        AdditionalFeature("housing.vacancy_rate", "Vacancy Rate", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 30), "%", "Empty units - market balance",
                          "Census"),
        AdditionalFeature("housing.construction_starts", "Construction Starts", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 2000000), "units/year", "New building permits",
                          "Census"),
        AdditionalFeature("housing.housing_affordability", "Housing Affordability", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 100), "%", "Income needed for median home",
                          "NAR"),
        AdditionalFeature("housing.mortgage_rate", "Mortgage Rate", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 20), "%", "30-year fixed - market rate",
                          "Freddie"),
        AdditionalFeature("housing.rent_burden", "Rent Burden", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 100), "%", "Income spent on rent - >30% is cost-burdened",
                          "HUD"),
        AdditionalFeature("housing.subprime_mortgage", "Subprime Mortgage", AdditionalSystem.HOUSING_SYSTEM,
                          (0, 1), "scale", "High-risk lending - 2008 crisis",
                          "Financial"),
    ]
    
    for f in features:
        if hasattr(f, 'feature_id'):
            ADDITIONAL_FEATURES[f.feature_id] = f


_register_additional_features()


def get_additional_feature(feature_id: str) -> AdditionalFeature:
    return ADDITIONAL_FEATURES.get(feature_id)


def get_additional_feature_count() -> int:
    return len(ADDITIONAL_FEATURES)


def get_all_additional_feature_ids() -> list:
    return list(ADDITIONAL_FEATURES.keys())