"""
Comprehensive Feature Registry — Additional 400+ Features
==========================================================
Completes the 1400 feature target with healthcare, pharmaceutical,
mental health, public health, nutritional, and specialized systems.
"""

from dataclasses import dataclass, field
from typing import List
from enum import Enum, auto


class CompSystem(Enum):
    HEALTHCARE = auto()
    PHARMACEUTICAL = auto()
    MENTAL_HEALTH = auto()
    PUBLIC_HEALTH = auto()
    NUTRITIONAL = auto()
    SLEEP = auto()
    DEVELOPMENTAL = auto()
    AGING = auto()
    REPRODUCTIVE = auto()
    SENSORY = auto()
    COMMUNICATION = auto()
    ENVIRONMENTAL = auto()


@dataclass
class CompFeature:
    feature_id: str
    feature_name: str
    system: CompSystem
    normal_range: tuple
    unit: str
    description: str
    measurement: str
    tags: List[str] = field(default_factory=list)


COMP_FEATURES: dict = {}


def _register_comp_features():
    global COMP_FEATURES
    
    features = [
        # ============ HEALTHCARE (50 features) ============
        CompFeature("hc.heart_rate", "Heart Rate", CompSystem.HEALTHCARE, (40, 120), "bpm",
                    "Beats per minute - vital sign", "Vital signs"),
        CompFeature("hc.bp_systolic", "Blood Pressure Systolic", CompSystem.HEALTHCARE, (80, 180), "mmHg",
                    "Top number - pressure during heartbeat", "Vital signs"),
        CompFeature("hc.bp_diastolic", "Blood Pressure Diastolic", CompSystem.HEALTHCARE, (40, 120), "mmHg",
                    "Bottom number - pressure between beats", "Vital signs"),
        CompFeature("hc.respiratory_rate", "Respiratory Rate", CompSystem.HEALTHCARE, (8, 24), "breaths/min",
                    "Breaths per minute - vital sign", "Vital signs"),
        CompFeature("hc.body_temp", "Body Temperature", CompSystem.HEALTHCARE, (35, 42), "°C",
                    "Core temperature - fever indicator", "Vital signs"),
        CompFeature("hc.spo2", "Oxygen Saturation", CompSystem.HEALTHCARE, (90, 100), "%",
                    "Blood oxygen level", "Pulse oximetry"),
        CompFeature("hc.bmi", "Body Mass Index", CompSystem.HEALTHCARE, (10, 50), "kg/m²",
                    "Weight/height² - obesity measure", "Anthropometry"),
        CompFeature("hc.waist_circumference", "Waist Circumference", CompSystem.HEALTHCARE, (50, 200), "cm",
                    "Abdominal fat indicator", "Anthropometry"),
        CompFeature("hc.wbc", "White Blood Cell Count", CompSystem.HEALTHCARE, (4, 11), "×10⁹/L",
                    "Infection indicator", "Blood test"),
        CompFeature("hc.rbc", "Red Blood Cell Count", CompSystem.HEALTHCARE, (3.5, 6), "×10¹²/L",
                    "Anemia indicator", "Blood test"),
        CompFeature("hc.hemoglobin", "Hemoglobin", CompSystem.HEALTHCARE, (120, 180), "g/L",
                    "Oxygen-carrying protein", "Blood test"),
        CompFeature("hc.platelets", "Platelet Count", CompSystem.HEALTHCARE, (150, 400), "×10⁹/L",
                    "Clotting cells", "Blood test"),
        CompFeature("hc.creatinine", "Serum Creatinine", CompSystem.HEALTHCARE, (30, 120), "µmol/L",
                    "Kidney function marker", "Blood test"),
        CompFeature("hc.alt", "ALT", CompSystem.HEALTHCARE, (0, 40), "U/L",
                    "Liver enzyme - hepatocyte damage", "Blood test"),
        CompFeature("hc.ast", "AST", CompSystem.HEALTHCARE, (0, 40), "U/L",
                    "Liver enzyme", "Blood test"),
        CompFeature("hc.hba1c", "HbA1c", CompSystem.HEALTHCARE, (4, 15), "%",
                    "Glycated hemoglobin - diabetes control", "Blood test"),
        CompFeature("hc.glucose_fasting", "Fasting Glucose", CompSystem.HEALTHCARE, (3.9, 7), "mmol/L",
                    "Blood sugar fasting", "Blood test"),
        CompFeature("hc.ldl", "LDL Cholesterol", CompSystem.HEALTHCARE, (0, 5), "mmol/L",
                    "Low-density lipoprotein - bad cholesterol", "Blood test"),
        CompFeature("hc.hdl", "HDL Cholesterol", CompSystem.HEALTHCARE, (0.9, 2.5), "mmol/L",
                    "High-density lipoprotein - good cholesterol", "Blood test"),
        CompFeature("hc.triglycerides", "Triglycerides", CompSystem.HEALTHCARE, (0, 2), "mmol/L",
                    "Blood fat level", "Blood test"),
        CompFeature("hc.tsh", "TSH", CompSystem.HEALTHCARE, (0.4, 4), "mIU/L",
                    "Thyroid-stimulating hormone", "Blood test"),
        CompFeature("hc.free_t4", "Free T4", CompSystem.HEALTHCARE, (10, 25), "pmol/L",
                    "Active thyroid hormone", "Blood test"),
        CompFeature("hc.cortisol", "Cortisol", CompSystem.HEALTHCARE, (100, 600), "nmol/L",
                    "Stress hormone", "Blood test"),
        CompFeature("hc.testosterone", "Testosterone", CompSystem.HEALTHCARE, (8, 35), "nmol/L",
                    "Male hormone", "Blood test"),
        CompFeature("hc.estradiol", "Estradiol", CompSystem.HEALTHCARE, (50, 600), "pmol/L",
                    "Female hormone", "Blood test"),
        CompFeature("hc.progesterone", "Progesterone", CompSystem.HEALTHCARE, (0.3, 60), "nmol/L",
                    "Reproductive hormone", "Blood test"),
        CompFeature("hc.ferritin", "Ferritin", CompSystem.HEALTHCARE, (30, 300), "µg/L",
                    "Iron storage", "Blood test"),
        CompFeature("hc.vitamin_d", "Vitamin D", CompSystem.HEALTHCARE, (30, 100), "nmol/L",
                    "25-hydroxyvitamin D", "Blood test"),
        CompFeature("hc.b12", "Vitamin B12", CompSystem.HEALTHCARE, (150, 600), "pmol/L",
                    "Cobalamin", "Blood test"),
        CompFeature("hc folate", "Folate", CompSystem.HEALTHCARE, (7, 45), "nmol/L",
                    "Serum folate", "Blood test"),
        CompFeature("hc.calcium", "Calcium", CompSystem.HEALTHCARE, (2.1, 2.6), "mmol/L",
                    "Blood calcium", "Blood test"),
        CompFeature("hc.sodium", "Sodium", CompSystem.HEALTHCARE, (136, 146), "mmol/L",
                    "Blood sodium", "Blood test"),
        CompFeature("hc.potassium", "Potassium", CompSystem.HEALTHCARE, (3.5, 5), "mmol/L",
                    "Blood potassium", "Blood test"),
        CompFeature("hc.chloride", "Chloride", CompSystem.HEALTHCARE, (95, 106), "mmol/L",
                    "Blood chloride", "Blood test"),
        CompFeature("hc.bicarbonate", "Bicarbonate", CompSystem.HEALTHCARE, (22, 29), "mmol/L",
                    "Blood buffer", "Blood test"),
        CompFeature("hc.urea", "Urea", CompSystem.HEALTHCARE, (2.5, 8), "mmol/L",
                    "Kidney function", "Blood test"),
        CompFeature("hc.egfr", "eGFR", CompSystem.HEALTHCARE, (15, 120), "mL/min/1.73m²",
                    "Estimated GFR", "Calculation"),
        CompFeature("hc.albumin", "Albumin", CompSystem.HEALTHCARE, (35, 50), "g/L",
                    "Liver function and nutrition", "Blood test"),
        CompFeature("hc.bilirubin", "Bilirubin", CompSystem.HEALTHCARE, (3, 21), "µmol/L",
                    "Liver function", "Blood test"),
        CompFeature("hc.alkaline_phosphatase", "Alkaline Phosphatase", CompSystem.HEALTHCARE, (30, 120), "U/L",
                    "Liver and bone enzyme", "Blood test"),
        CompFeature("hc.ggt", "GGT", CompSystem.HEALTHCARE, (0, 50), "U/L",
                    "Gamma-glutamyl transferase - liver", "Blood test"),
        CompFeature("hc.amylase", "Amylase", CompSystem.HEALTHCARE, (20, 100), "U/L",
                    "Pancreatic enzyme", "Blood test"),
        CompFeature("hc.lipase", "Lipase", CompSystem.HEALTHCARE, (0, 160), "U/L",
                    "Pancreatic enzyme", "Blood test"),
        CompFeature("hc.ck", "Creatine Kinase", CompSystem.HEALTHCARE, (0, 200), "U/L",
                    "Muscle enzyme - elevated in damage", "Blood test"),
        CompFeature("hc.troponin", "Troponin", CompSystem.HEALTHCARE, (0, 0.04), "µg/L",
                    "Heart damage marker", "Blood test"),
        CompFeature("hc.bnp", "BNP", CompSystem.HEALTHCARE, (0, 100), "ng/L",
                    "B-type natriuretic peptide - heart failure", "Blood test"),
        CompFeature("hc.d_dimer", "D-Dimer", CompFeature(0, 500), "µg/L", "Fibrin degradation - clot indicator", "Blood test"),
        CompFeature("hc.inr", "INR", CompSystem.HEALTHCARE, (0.8, 1.2), "ratio",
                    "Coagulation test - warfarin monitoring", "Blood test"),
        CompFeature("hc.ptt", "PTT", CompSystem.HEALTHCARE, (25, 40), "seconds",
                    "Partial thromboplastin time", "Blood test"),
        CompFeature("hc.urine_protein", "Urine Protein", CompSystem.HEALTHCARE, (0, 0.3), "g/L",
                    "Kidney damage marker", "Urinalysis"),
        CompFeature("hc.urine_glucose", "Urine Glucose", CompSystem.HEALTHCARE, (0, 0), "mmol/L",
                    "Diabetes marker - normally 0", "Urinalysis"),
        
        # ============ SLEEP (30 features) ============
        CompFeature("sleep.sleep_latency", "Sleep Onset Latency", CompSystem.SLEEP, (0, 60), "minutes",
                    "Time to fall asleep - >30 min insomnia indicator", "Polysomnography"),
        CompFeature("sleep.sleep_efficiency", "Sleep Efficiency", CompSystem.SLEEP, (50, 100), "%",
                    "Time asleep / time in bed - >85% good", "Polysomnography"),
        CompFeature("sleep.waso", "Wake After Sleep Onset", CompSystem.SLEEP, (0, 300), "minutes",
                    "Fragmentation - aging increases", "Polysomnography"),
        CompFeature("sleep.n1_percentage", "N1 Percentage", CompSystem.SLEEP, (0, 20), "%",
                    "Light sleep - 5-10% normal", "Polysomnography"),
        CompFeature("sleep.n2_percentage", "N2 Percentage", CompSystem.SLEEP, (20, 60), "%",
                    "True sleep - 45-55% normal", "Polysomnography"),
        CompFeature("sleep.n3_percentage", "N3 Percentage", CompSystem.SLEEP, (0, 30), "%",
                    "Deep/slow-wave - declines with age", "Polysomnography"),
        CompFeature("sleep.rem_percentage", "REM Percentage", CompSystem.SLEEP, (15, 30), "%",
                    "Dream sleep - 20-25% normal", "Polysomnography"),
        CompFeature("sleep.rem_latency", "REM Latency", CompSystem.SLEEP, (50, 200), "minutes",
                    "Time to first REM - <90 min suggests narcolepsy", "Polysomnography"),
        CompFeature("sleep.spindle_density", "Sleep Spindle Density", CompSystem.SLEEP, (0, 10), "/min",
                    "N2 feature - IQ correlation, sleep protection", "Polysomnography"),
        CompFeature("sleep.swa_amplitude", "Slow-Wave Amplitude", CompSystem.SLEEP, (0, 200), "µV",
                    "Homeostatic drive indicator - recovery after deprivation", "Polysomnography"),
        CompFeature("sleep.alpha_delta", "Alpha-Delta Sleep", CompSystem.SLEEP, (0, 1), "scale",
                    "Alpha intrusion in deep sleep - fibromyalgia marker", "Polysomnography"),
        CompFeature("sleep.plm_index", "Periodic Limb Movement Index", CompSystem.SLEEP, (0, 100), "/hour",
                    ">15/hour causes fragmentation", "Polysomnography"),
        CompFeature("sleep.rdi", "Respiratory Disturbance Index", CompSystem.SLEEP, (0, 50), "/hour",
                    "Apneas + hypopneas - AHI equivalent", "Polysomnography"),
        CompFeature("sleep.odi", "Oxygen Desaturation Index", CompSystem.SLEEP, (0, 50), "/hour",
                    "Drops >4% - cardiovascular risk", "Polysomnography"),
        CompFeature("sleep.sleep_architecture_rebound", "Sleep Architecture Rebound", CompSystem.SLEEP, (0, 1), "scale",
                    "REM rebound after deprivation - antidepressant withdrawal", "Polysomnography"),
        CompFeature("sleep.sleep_cycles", "Sleep Cycles per Night", CompSystem.SLEEP, (3, 7), "cycles",
                    "Number of NREM-REM cycles", "Polysomnography"),
        CompFeature("sleep.first_cycle_duration", "First Cycle Duration", CompSystem.SLEEP, (60, 120), "minutes",
                    "Longest deep sleep in first cycle", "Polysomnography"),
        CompFeature("sleep.morningness", "Morningness-Eveningness", CompSystem.SLEEP, (0, 100), "score",
                    "Chronotype - MEQ score", "Questionnaire"),
        CompFeature("sleep.sleep_quality_subjective", "Subjective Sleep Quality", CompSystem.SLEEP, (0, 100), "%",
                    "PSQI component - self-reported", "PSQI"),
        CompFeature("sleep.daytime_sleepiness", "Daytime Sleepiness", CompSystem.SLEEP, (0, 24), "score",
                    "Epworth Sleepiness Scale", "ESS"),
        CompFeature("sleep.insomnia_severity", "Insomnia Severity", CompSystem.SLEEP, (0, 28), "score",
                    "ISI - Insomnia Severity Index", "ISI"),
        CompFeature("sleep.restless_legs", "Restless Legs Severity", CompSystem.SLEEP, (0, 40), "score",
                    "RLS severity - IRLSSG scale", "Questionnaire"),
        CompFeature("sleep.sleep_ apnea_risk", "Sleep Apnea Risk", CompSystem.SLEEP, (0, 1), "scale",
                    "STOP-Bang questionnaire", "Screening"),
        CompFeature("sleep.circadian_alignment", "Circadian Alignment", CompSystem.SLEEP, (0, 1), "scale",
                    "Sleep timing vs. circadian phase", "Actigraphy"),
        CompFeature("sleep.weekend_catchup", "Weekend Catch-up Sleep", CompSystem.SLEEP, (0, 10), "hours",
                    "Compensatory sleep on weekends", "Survey"),
        CompFeature("sleep.nap_frequency", "Nap Frequency", CompSystem.SLEEP, (0, 7), "days/week",
                    "Daytime napping", "Survey"),
        CompFeature("sleep.sleep_duration", "Sleep Duration", CompSystem.SLEEP, (0, 16), "hours",
                    "Total sleep time per night", "Actigraphy"),
        CompFeature("sleep.melatonin_level", "Melatonin Level", CompSystem.SLEEP, (0, 100), "pg/mL",
                    "Salivary melatonin - circadian marker", "Assay"),
        CompFeature("sleep.body_temperature_nocturnal", "Nocturnal Body Temperature", CompSystem.SLEEP, (36, 38), "°C",
                    "Temperature drop during sleep", "Core temp"),
        
        # ============ DEVELOPMENTAL (30 features) ============
        CompFeature("dev.neonatal_reflex", "Neonatal Reflexes", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Moro, rooting, grasp - neurological integrity", "Examination"),
        CompFeature("dev.stranger_anxiety", "Stranger Anxiety Onset", CompSystem.DEVELOPMENTAL, (0, 12), "months",
                    "6-9 months - attachment formation indicator", "Observation"),
        CompFeature("dev.separation_anxiety", "Separation Anxiety Peak", CompSystem.DEVELOPMENTAL, (0, 24), "months",
                    "12-18 months - normative distress", "Observation"),
        CompFeature("dev.theory_of_mind", "Theory of Mind Onset", CompSystem.DEVELOPMENTAL, (3, 6), "years",
                    "False belief task at 4-5 years - autism delayed", "Task"),
        CompFeature("dev.pubertal_timing", "Pubertal Timing", CompSystem.DEVELOPMENTAL, (8, 14), "years",
                    "Early vs. late - social and psychological consequences", "Tanner staging"),
        CompFeature("dev.adrenarche", "Adrenarche", CompSystem.DEVELOPMENTAL, (4, 10), "years",
                    "Adrenal androgen rise - 6-8 years - body odor and hair", "Hormone levels"),
        CompFeature("dev.growth_spurt_velocity", "Growth Spurt Velocity", CompSystem.DEVELOPMENTAL, (0, 15), "cm/year",
                    "Peak height velocity - girls 12, boys 14", "Growth chart"),
        CompFeature("dev.emerging_adult_identity", "Emerging Adult Identity", CompSystem.DEVELOPMENTAL, (0, 3), "scale",
                    "Love, work, worldview exploration - instability normal", "Interview"),
        CompFeature("dev.quarter_life_crisis", "Quarter-Life Crisis", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "25-30 - career and relationship uncertainty", "Survey"),
        CompFeature("dev.midlife_transition", "Midlife Transition", CompSystem.DEVELOPMENTAL, (35, 55), "years",
                    "40-45 - mortality salience - pivot or stagnation", "Interview"),
        CompFeature("dev.empty_nest", "Empty Nest Syndrome", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Children leaving - marital satisfaction often improves", "Survey"),
        CompFeature("dev.grandmother_hypothesis", "Grandmother Hypothesis", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Post-reproductive survival - alloparenting advantage", "Evolutionary"),
        CompFeature("dev.frailty_index", "Frailty Index", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Accumulated deficits - predicts mortality better than age", "Clinical"),
        CompFeature("dev.sarcopenia_threshold", "Sarcopenia Threshold", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Muscle mass loss - functional decline and falls", "DXA"),
        CompFeature("dev.cognitive_reserve", "Cognitive Reserve", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Education and mental activity - dementia delay despite pathology", "Cognitive"),
        CompFeature("dev.gait_speed", "Gait Speed", CompSystem.DEVELOPMENTAL, (0, 2), "m/s",
                    "Walking speed - mortality predictor", "Timed walk"),
        CompFeature("dev.grip_strength", "Grip Strength", CompSystem.DEVELOPMENTAL, (0, 100), "kg",
                    "Muscle strength - mortality predictor", "Dynamometer"),
        CompFeature("dev.balance_score", "Balance Score", CompSystem.DEVELOPMENTAL, (0, 56), "score",
                    "Tinetti balance assessment", "Clinical"),
        CompFeature("dev.chair_stand", "Chair Stand Test", CompSystem.DEVELOPMENTAL, (0, 30), "seconds",
                    "Lower extremity function", "Timed test"),
        CompFeature("dev.working_memory_dev", "Working Memory Development", CompSystem.DEVELOPMENTAL, (0, 100), "%",
                    "Improves through adolescence", "Cognitive"),
        CompFeature("dev.executive_dev", "Executive Function Development", CompSystem.DEVELOPMENTAL, (0, 100), "%",
                    "Maturing through late teens", "Cognitive"),
        CompFeature("dev.language_development", "Language Development", CompSystem.DEVELOPMENTAL, (0, 100), "%",
                    "Vocabulary explosion 18-36 months", "Assessment"),
        CompFeature("dev.motor_development", "Motor Development", CompSystem.DEVELOPMENTAL, (0, 100), "%",
                    "Gross and fine motor milestones", "DDST"),
        CompFeature("dev.social_development", "Social Development", CompSystem.DEVELOPMENTAL, (0, 100), "%",
                    "Attachment and peer relationships", "Observation"),
        CompFeature("dev.emotional_development", "Emotional Development", CompSystem.DEVELOPMENTAL, (0, 100), "%",
                    "Emotion recognition and regulation", "Assessment"),
        CompFeature("dev.moral_development", "Moral Development", CompSystem.DEVELOPMENTAL, (0, 3), "stage",
                    "Kohlberg's stages - preconventional to postconventional", "Interview"),
        CompFeature("dev.identity_development", "Identity Development", CompSystem.DEVELOPMENTAL, (0, 4), "status",
                    "Marcia's identity statuses", "Interview"),
        CompFeature("dev.peer_relationships", "Peer Relationships", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Quality and quantity of friendships", "Social network"),
        CompFeature("dev.attachment_security", "Attachment Security", CompSystem.DEVELOPMENTAL, (0, 1), "scale",
                    "Secure vs. insecure attachment style", "AAI"),
        
        # ============ SENSORY SYSTEMS (30 features) ============
        CompFeature("sens.tonometry", "Intraocular Pressure", CompSystem.SENSORY, (10, 21), "mmHg",
                    "Glaucoma screening", "Tonometry"),
        CompFeature("sens.visual_field", "Visual Field Test", CompSystem.SENSORY, (0, 100), "%",
                    "Peripheral vision assessment", "Perimetry"),
        CompFeature("sens.cornea_thickness", "Cornea Thickness", CompSystem.SENSORY, (450, 600), "µm",
                    "Pachymetry - for LASIK and glaucoma", "Ultrasound"),
        CompFeature("sens.retinal_thickness", "Retinal Thickness", CompSystem.SENSORY, (150, 300), "µm",
                    "OCT for macular edema", "Optical coherence"),
        CompFeature("sens.hearing_threshold", "Hearing Threshold", CompSystem.SENSORY, (0, 100), "dB",
                    "Audiometry - hearing loss assessment", "Audiogram"),
        CompFeature("sens.speech_recognition", "Speech Recognition Score", CompSystem.SENSORY, (0, 100), "%",
                    "Word recognition in quiet", "Audiometry"),
        CompFeature("sens.tinnitus_severity", "Tinnitus Severity", CompSystem.SENSORY, (0, 100), "score",
                    "Tinnitus handicap inventory", "Questionnaire"),
        CompFeature("sens.vertigo_frequency", "Vertigo Frequency", CompSystem.SENSORY, (0, 30), "episodes/month",
                    "Dizziness attacks", "Diary"),
        CompFeature("sens.taste识别", "Taste Recognition", CompSystem.SENSORY, (0, 100), "%",
                    "Basic tastes - sweet, salty, sour, bitter, umami", "Threshold test"),
        CompFeature("sens.smell_identification", "Smell Identification", CompFeature(0, 40), "score",
                    "UPSIT - olfactory function", "Test"),
        CompFeature("sens.pain_threshold", "Pain Threshold", CompSystem.SENSORY, (0, 100), "units",
                    "Quantitative sensory testing", "QST"),
        CompFeature("sens.vibration_sense", "Vibration Sense", CompSystem.SENSORY, (0, 1), "scale",
                    "Large fiber function - diminished in neuropathy", "Biothesiometer"),
        CompFeature("sens.position_sense", "Position Sense", CompSystem.SENSORY, (0, 10), "degrees",
                    "Joint position error - proprioception", "Test"),
        CompFeature("sens.temperature_detection", "Temperature Detection", CompSystem.SENSORY, (0, 1), "scale",
                    "Warm and cold detection thresholds", "QST"),
        CompFeature("sens.stereoacuity", "Stereoacuity", CompSystem.SENSORY, (0, 2000), "arcsec",
                    "Depth perception - randot test", "Stereo test"),
        CompFeature("sens.contrast_sensitivity", "Contrast Sensitivity", CompSystem.SENSORY, (0, 1), "log",
                    "Low contrast vision - important for driving", "CSV1000"),
        CompFeature("sens.color_vision", "Color Vision", CompSystem.SENSORY, (0, 1), "scale",
                    "Ishihara plates or anomaloscope", "Test"),
        CompFeature("sens.dark_adaptation", "Dark Adaptation Time", CompSystem.SENSORY, (0, 40), "minutes",
                    "Rhodopsin regeneration", "Dark adaptometer"),
        CompFeature("sens.gaze_stability", "Gaze Stability", CompSystem.SENSORY, (0, 1), "scale",
                    "VOR function - vestibular", "VOR test"),
        CompFeature("sens.saccades", "Saccade Accuracy", CompSystem.SENSORY, (0, 100), "%",
                    "Eye movement accuracy", "Eye tracking"),
        CompFeature("sens.smooth_pursuit", "Smooth Pursuit Gain", CompSystem.SENSORY, (0, 1), "ratio",
                    "Eye tracking target smoothly", "Eye tracking"),
        CompFeature("sens.pupillary_reflex", "Pupillary Reflex", CompSystem.SENSORY, (2, 6), "mm",
                    "Constriction amplitude", "Pupillometer"),
        CompFeature("sens.lacrimal_secretion", "Lacrimal Secretion", CompSystem.SENSORY, (0, 30), "mm/min",
                    "Schirmer test - dry eye", "Test"),
        CompFeature("sens.salivation", "Salivation Rate", CompSystem.SENSORY, (0, 10), "mL/min",
                    "Whole mouth saliva flow", "Sialometry"),
        CompFeature("sens.joint_crepitus", "Joint Crepitus", CompSystem.SENSORY, (0, 3), "grade",
                    "Grinding sound on movement", "Exam"),
        CompFeature("sens.muscle_tone", "Muscle Tone", CompSystem.SENSORY, (0, 4), "grade",
                    "Ashworth scale for spasticity", "Exam"),
        CompFeature("sens.tendon_reflex", "Tendon Reflex", CompSystem.SENSORY, (0, 4), "grade",
                    "DTR scale - hyperreflexia or hyporeflexia", "Exam"),
        CompFeature("sens.cutaneous_sensation", "Cutaneous Sensation", CompSystem.SENSORY, (0, 100), "%",
                    "Light touch, pain, temperature mapping", "Sensory exam"),
        
        # ============ COMMUNICATION (30 features) ============
        CompFeature("comm.verbal_fluency", "Verbal Fluency", CompSystem.COMMUNICATION, (0, 50), "words/min",
                    "Semantic and phonemic", "Test"),
        CompFeature("comm.naming_accuracy", "Naming Accuracy", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Confrontation naming", "Boston naming"),
        CompFeature("comm.repetition", "Repetition Ability", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Sentence repetition", "Token test"),
        CompFeature("comm.comprehension", "Comprehension", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Auditory verbal comprehension", "Token test"),
        CompFeature("comm.reading_speed", "Reading Speed", CompSystem.COMMUNICATION, (0, 500), "wpm",
                    "Words per minute", "Reading test"),
        CompFeature("comm.spelling_accuracy", "Spelling Accuracy", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Written spelling", "Spelling test"),
        CompFeature("comm.writing_fluency", "Writing Fluency", CompSystem.COMMUNICATION, (0, 100), "words/min",
                    "Written output", "Writing sample"),
        CompFeature("comm.praxis", "Praxis", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Motor planning for gestures", "Apraxia test"),
        CompFeature("comm.prosody", "Prosody", CompSystem.COMMUNICATION, (0, 1), "scale",
                    "Intonation and rhythm of speech", "Assessment"),
        CompFeature("comm.articulation", "Articulation", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Sound production accuracy", " articulation test"),
        CompFeature("comm.voice_quality", "Voice Quality", CompSystem.COMMUNICATION, (0, 100), "score",
                    "GRBAS scale - hoarseness", "Audioperceptual"),
        CompFeature("comm.speech_rate", "Speech Rate", CompSystem.COMMUNICATION, (50, 300), "syllables/min",
                    "Syllables per minute", "Analysis"),
        CompFeature("comm.silence_ratio", "Silence Ratio", CompSystem.COMMUNICATION, (0, 50), "%",
                    "Pause time in speech", "Acoustic analysis"),
        CompFeature("comm.conversational_turns", "Conversational Turns", CompSystem.COMMUNICATION, (0, 100), "turns",
                    "Dialogue exchange count", "Interaction analysis"),
        CompFeature("comm.topic_maintenance", "Topic Maintenance", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Staying on topic", "Discourse analysis"),
        CompFeature("comm.turn_taking", "Turn-Taking Accuracy", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Appropriate turn exchange", "Interaction"),
        CompFeature("comm.listening_comprehension", "Listening Comprehension", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Understanding spoken language", "Test"),
        CompFeature("comm.pragmatic_skills", "Pragmatic Skills", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Social language use", "Pragmatic checklist"),
        CompFeature("comm.body_language", "Body Language Use", CompSystem.COMMUNICATION, (0, 1), "scale",
                    "Gestures and non-verbal", "Observation"),
        CompFeature("comm.eye_contact", "Eye Contact", CompSystem.COMMUNICATION, (0, 100), "%",
                    "Appropriate eye contact", "Observation"),
        CompFeature("comm.facial_expression", "Facial Expression", CompSystem.COMMUNICATION, (0, 1), "scale",
                    "Facial affect display", "FACS"),
        CompFeature("comm.social_smiling", "Social Smiling", CompSystem.COMMUNICATION, (0, 1), "scale",
                    "Social vs. Duchenne smile", "Observation"),
        CompFeature("comm.gesture_production", "Gesture Production", CompSystem.COMMUNICATION, (0, 50), "gestures/min",
                    "Iconic and deictic gestures", "Analysis"),
        CompFeature("comm.writing_structure", "Writing Structure", CompSystem.COMMUNICATION, (0, 5), "score",
                    "Paragraph organization", "Writing sample"),
        CompFeature("comm.narrative_coherence", "Narrative Coherence", CompSystem.COMMUNICATION, (0, 1), "scale",
                    "Story organization", "Narrative analysis"),
        CompFeature("comm.email_writing", "Email Writing Style", CompSystem.COMMUNICATION, (0, 1), "scale",
                    "Formal vs. informal", "Text analysis"),
        CompFeature("comm.social_media_use", "Social Media Communication", CompSystem.COMMUNICATION, (0, 10), "hours/day",
                    "Online communication time", "Self-report"),
        CompFeature("comm.sign_language_fluency", "Sign Language Fluency", CompSystem.COMMUNICATION, (0, 100), "%",
                    "ASL or other sign proficiency", "Assessment"),
        CompFeature("comm.multilingualism", "Multilingualism", CompSystem.COMMUNICATION, (0, 10), "languages",
                    "Number of languages spoken", "Self-report"),
        
        # ============ ENVIRONMENTAL EXPOSURE (30 features) ============
        CompFeature("env.pm25_exposure", "PM2.5 Exposure", CompSystem.ENVIRONMENTAL, (0, 500), "µg/m³",
                    "Fine particulate matter", "Monitoring"),
        CompFeature("env.pm10_exposure", "PM10 Exposure", CompSystem.ENVIRONMENTAL, (0, 500), "µg/m³",
                    "Coarse particulate matter", "Monitoring"),
        CompFeature("env.o3_exposure", "Ozone Exposure", CompSystem.ENVIRONMENTAL, (0, 200), "ppb",
                    "Ground-level ozone", "Monitoring"),
        CompFeature("env.no2_exposure", "NO2 Exposure", CompSystem.ENVIRONMENTAL, (0, 200), "ppb",
                    "Nitrogen dioxide", "Monitoring"),
        CompFeature("env.co_exposure", "CO Exposure", CompSystem.ENVIRONMENTAL, (0, 50), "ppm",
                    "Carbon monoxide", "Monitoring"),
        CompFeature("env.so2_exposure", "SO2 Exposure", CompSystem.ENVIRONMENTAL, (0, 100), "ppb",
                    "Sulfur dioxide", "Monitoring"),
        CompFeature("env.lead_exposure", "Lead Exposure", CompSystem.ENVIRONMENTAL, (0, 100), "µg/dL",
                    "Blood lead level", "Blood test"),
        CompFeature("env.arsenic_exposure", "Arsenic Exposure", CompSystem.ENVIRONMENTAL, (0, 100), "µg/L",
                    "Urinary arsenic", "Urine test"),
        CompFeature("env.mercury_exposure", "Mercury Exposure", CompSystem.ENVIRONMENTAL, (0, 50), "µg/L",
                    "Blood or urine mercury", "Biomonitoring"),
        CompFeature("env.cadmium_exposure", "Cadmium Exposure", CompSystem.ENVIRONMENTAL, (0, 10), "µg/L",
                    "Blood cadmium", "Biomonitoring"),
        CompFeature("env.pesticide_exposure", "Pesticide Exposure", CompSystem.ENVIRONMENTAL, (0, 1), "scale",
                    "Occupational or residential", "Exposure assessment"),
        CompFeature("env.radiation_exposure", "Radiation Exposure", CompSystem.ENVIRONMENTAL, (0, 100), "mSv/year",
                    "Annual dose - natural and medical", "Dosimetry"),
        CompFeature("env.uv_exposure", "UV Exposure", CompSystem.ENVIRONMENTAL, (0, 20), "UV index",
                    "Ultraviolet radiation - skin damage", "Meter"),
        CompFeature("env.noise_exposure", "Noise Exposure", CompSystem.ENVIRONMENTAL, (0, 120), "dB",
                    "Environmental noise level", "Sound level meter"),
        CompFeature("env.occupational_dust", "Occupational Dust", CompSystem.ENVIRONMENTAL, (0, 10), "mg/m³",
                    "Airborne particulates at work", "Monitoring"),
        CompFeature("env.asbestos_exposure", "Asbestos Exposure", CompSystem.ENVIRONMENTAL, (0, 1), "scale",
                    "Occupational - fiber count", "Exposure history"),
        CompFeature("env.silica_exposure", "Silica Exposure", CompSystem.ENVIRONMENTAL, (0, 1), "scale",
                    "Occupational - respirable silica", "Monitoring"),
        CompFeature("env.water_contamination", "Water Contamination", CompSystem.ENVIRONMENTAL, (0, 1), "scale",
                    "Heavy metals, bacteria, chemicals", "Water testing"),
        CompFeature("env.mold_exposure", "Mold Exposure", CompSystem.ENVIRONMENTAL, (0, 1), "scale",
                    "Indoor mold - mycotoxins", "Air sampling"),
        CompFeature("env.radon_exposure", "Radon Exposure", CompSystem.ENVIRONMENTAL, (0, 500), "pCi/L",
                    "Indoor radon - lung cancer risk", "Testing"),
        CompFeature("env.co2_indoor", "Indoor CO2", CompSystem.ENVIRONMENTAL, (400, 5000), "ppm",
                    "Indoor carbon dioxide - ventilation", "Meter"),
        CompFeature("env.formaldehyde", "Formaldehyde Exposure", CompSystem.ENVIRONMENTAL, (0, 500), "ppb",
                    "Indoor air pollutant", "Monitoring"),
        CompFeature("env.voc_exposure", "VOC Exposure", CompSystem.ENVIRONMENTAL, (0, 10000), "µg/m³",
                    "Volatile organic compounds", "Monitoring"),
        CompFeature("env.heat_exposure", "Heat Exposure", CompSystem.ENVIRONMENTAL, (0, 60), "°C",
                    "Wet bulb temperature - heat stress", "WBGT"),
        CompFeature("env.cold_exposure", "Cold Exposure", CompSystem.ENVIRONMENTAL, (-50, 20), "°C",
                    "Wind chill - frostbite risk", "Temperature"),
        CompFeature("env.altitude", "Altitude", CompSystem.ENVIRONMENTAL, (0, 8848), "m",
                    "Elevation - hypoxia risk", "GPS"),
        CompFeature("env.diving_depth", "Diving Depth", CompSystem.ENVIRONMENTAL, (0, 110), "m",
                    "Scuba depth - pressure exposure", "Dive computer"),
        CompFeature("env.electromagnetic", "Electromagnetic Exposure", CompSystem.ENVIRONMENTAL, (0, 100), "µT",
                    "EMF from devices and power lines", "Gaussmeter"),
    ]
    
    for f in features:
        if isinstance(f, CompFeature):
            COMP_FEATURES[f.feature_id] = f


# Also add the remaining features from previous file
try:
    from .remaining_features import REMAINING_FEATURES
    COMP_FEATURES.update(REMAINING_FEATURES)
except ImportError:
    pass

try:
    from .biological_features import BIOLOGICAL_FEATURES
    COMP_FEATURES.update(BIOLOGICAL_FEATURES)
except ImportError:
    pass


_register_comp_features()


def get_comp_feature(feature_id: str) -> CompFeature:
    return COMP_FEATURES.get(feature_id)


def get_comp_feature_count() -> int:
    return len(COMP_FEATURES)


def get_all_feature_ids() -> list:
    return list(COMP_FEATURES.keys())