"""
Complete Feature Set - Final 400+ Features
==========================================
Completes the 1400 feature target.
"""

from dataclasses import dataclass, field
from typing import List
from enum import Enum, auto


class FinalSystem(Enum):
    ADDITIONAL_MEDICAL = auto()
    ADDITIONAL_PSYCH = auto()
    ADDITIONAL_SOCIAL = auto()
    ADDITIONAL_ENVIRONMENTAL = auto()
    ADDITIONAL_TECHNOLOGY = auto()
    ADDITIONAL_LEGAL = auto()
    ADDITIONAL_SPIRITUAL = auto()
    ADDITIONAL_ARTS = auto()
    ADDITIONAL_LANGUAGE = auto()


@dataclass
class FinalFeature:
    feature_id: str
    feature_name: str
    system: FinalSystem
    normal_range: tuple
    unit: str
    description: str
    measurement: str
    tags: List[str] = field(default_factory=list)


FINAL_FEATURES: dict = {}


def _register_final_features():
    global FINAL_FEATURES
    
    features = [
        # ============ MEDICAL CONDITIONS (100 features) ============
        FinalFeature("med.hypertension", "Hypertension", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "stage",
                    "BP ≥140/90 - essential vs secondary", "BP measurement"),
        FinalFeature("med.type1_diabetes", "Type 1 Diabetes", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Autoimmune beta cell destruction", "HbA1c, antibodies"),
        FinalFeature("med.type2_diabetes", "Type 2 Diabetes", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Insulin resistance and relative deficiency", "HbA1c"),
        FinalFeature("med.gestational_diabetes", "Gestational Diabetes", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Pregnancy-induced glucose intolerance", "OGTT"),
        FinalFeature("med.copd", "COPD", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "Chronic obstructive pulmonary disease", "Spirometry"),
        FinalFeature("med.asthma", "Asthma", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "severity",
                    "Airway hyperresponsiveness", "Spirometry, triggers"),
        FinalFeature("med.cystic_fibrosis", "Cystic Fibrosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "CFTR mutation - chronic lung disease", "Genetic test"),
        FinalFeature("med.lung_cancer", "Lung Cancer", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "Non-small cell vs small cell", "Biopsy, imaging"),
        FinalFeature("med.breast_cancer", "Breast Cancer", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "ER+, HER2+, triple negative subtypes", "Biopsy"),
        FinalFeature("med.colorectal_cancer", "Colorectal Cancer", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "Colonoscopy and biopsy", "Histology"),
        FinalFeature("med.prostate_cancer", "Prostate Cancer", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "PSA, Gleason score", "Biopsy"),
        FinalFeature("med.melanoma", "Melanoma", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "Skin cancer - ABCDE criteria", "Biopsy"),
        FinalFeature("med.leukemia", "Leukemia", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "type",
                    "Acute vs chronic, myeloid vs lymphoid", "Blood smear"),
        FinalFeature("med.lymphoma", "Lymphoma", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "type",
                    "Hodgkin vs non-Hodgkin", "Biopsy"),
        FinalFeature("med.coronary_artery_disease", "Coronary Artery Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "CAD - plaque in coronary arteries", "Angiography"),
        FinalFeature("med.heart_failure", "Heart Failure", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "HFrEF vs HFpEF", "Echo, BNP"),
        FinalFeature("med.atrial_fibrillation", "Atrial Fibrillation", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "type",
                    "AF - irregularly irregular rhythm", "ECG"),
        FinalFeature("med.strok", "Stroke", FinalSystem.ADDITIONAL_MEDICAL, (0, 5), "type",
                    "Ischemic vs hemorrhagic vs TIA", "CT/MRI"),
        FinalFeature("med.alzheimer", "Alzheimer Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "stage",
                    "Most common dementia", "Clinical, biomarkers"),
        FinalFeature("med.parkinson", "Parkinson Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 5), "stage",
                    "Movement disorder - Lewy bodies", "Clinical"),
        FinalFeature("med.ms", "Multiple Sclerosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "type",
                    "RRMS, SPMS, PPMS", "MRI, CSF"),
        FinalFeature("med.epilepsy", "Epilepsy", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Seizure disorder - focal vs generalized", "EEG"),
        FinalFeature("med.migraine", "Migraine", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "With vs without aura", "Clinical"),
        FinalFeature("med.rheumatoid_arthritis", "Rheumatoid Arthritis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Autoimmune joint disease", "RF, anti-CCP"),
        FinalFeature("med.osteoarthritis", "Osteoarthritis", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "grade",
                    "Degenerative joint disease", "X-ray"),
        FinalFeature("med.osteoporosis", "Osteoporosis", FinalSystem.ADDITIONAL_MEDICAL, (-4, 0), "T-score",
                    "BMD T-score ≤-2.5", "DXA"),
        FinalFeature("med.lupus", "Systemic Lupus Erythematosus", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "SLE - autoimmune multi-organ", "ANA, dsDNA"),
        FinalFeature("med.psoriasis", "Psoriasis", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Skin disease - PASI score", "Clinical"),
        FinalFeature("med.inflammatory_bowel", "Inflammatory Bowel Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 2), "type",
                    "Crohn vs UC", "Endoscopy"),
        FinalFeature("med.cirrhosis", "Cirrhosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "End-stage liver fibrosis", "Biopsy, elastography"),
        FinalFeature("med.chronic_kidney_disease", "Chronic Kidney Disease", FinalSystem.ADDITIONAL_MEDICAL, (1, 5), "stage",
                    "CKD stages 1-5", "eGFR"),
        FinalFeature("med.glomerulonephritis", "Glomerulonephritis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Proteinuria, hematuria", "Biopsy"),
        FinalFeature("med.pkd", "Polycystic Kidney Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "ADPKD - genetic", "Imaging"),
        FinalFeature("med.celiac_disease", "Celiac Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Gluten sensitivity - villous atrophy", "Biopsy, tTG"),
        FinalFeature("med.hypothyroidism", "Hypothyroidism", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Underactive thyroid - Hashimoto", "TSH, free T4"),
        FinalFeature("med.hyperthyroidism", "Hyperthyroidism", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Overactive thyroid - Graves", "TSH, free T4"),
        FinalFeature("med.addison", "Addison Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Adrenal insufficiency", "Cortisol, ACTH"),
        FinalFeature("med.cushing", "Cushing Syndrome", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Cortisol excess", "Cortisol, dexamethasone"),
        FinalFeature("med.pheochromocytoma", "Pheochromocytoma", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Catecholamine-secreting tumor", "Metanephrines"),
        FinalFeature("med.primary_hyperaldosteronism", "Primary Hyperaldosteronism", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Conn syndrome - hypertension", "ARR"),
        FinalFeature("med.acromegaly", "Acromegaly", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "GH excess - IGF-1 elevated", "IGF-1, OGTT"),
        FinalFeature("med.pcos", "Polycystic Ovary Syndrome", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Hyperandrogenism, anovulation, insulin resistance", "Clinical"),
        FinalFeature("med.endometriosis", "Endometriosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Uterine tissue outside uterus", "Laparoscopy"),
        FinalFeature("med.uterine_fibroids", "Uterine Fibroids", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Leiomyomas - benign tumor", "Ultrasound"),
        FinalFeature("med.bph", "Benign Prostatic Hyperplasia", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Prostate enlargement", "IPSS"),
        FinalFeature("med.copd_exacerbation", "COPD Exacerbation", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Acute worsening - hospitalization", "Clinical"),
        FinalFeature("med.asthma_exacerbation", "Asthma Exacerbation", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Acute asthma attack", "PEF, symptoms"),
        FinalFeature("med.dehydration", "Dehydration", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "grade",
                    "Hypovolemia - isotonic most common", "Clinical, labs"),
        FinalFeature("med.hypovolemia", "Hypovolemia", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Volume depletion", "Clinical"),
        FinalFeature("med.hypervolemia", "Hypervolemia", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Volume overload - edema", "Clinical"),
        FinalFeature("med.acid_base_disorder", "Acid-Base Disorder", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "type",
                    "Metabolic vs respiratory acidosis/alkalosis", "ABG"),
        FinalFeature("med.electrolyte_imbalance", "Electrolyte Imbalance", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Na, K, Ca, Mg abnormalities", "Labs"),
        FinalFeature("med.anemia", "Anemia", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Low hemoglobin - many causes", "CBC"),
        FinalFeature("med.polycythemia", "Polycythemia", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Elevated RBC - relative vs absolute", "CBC"),
        FinalFeature("med.thrombocytopenia", "Thrombocytopenia", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Low platelets - ITP, sequestration", "CBC"),
        FinalFeature("med.thrombocytosis", "Thrombocytosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Elevated platelets - reactive vs clonal", "CBC"),
        FinalFeature("med.leukopenia", "Leukopenia", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Low white blood cells", "CBC"),
        FinalFeature("med.leukocytosis", "Leukocytosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Elevated white blood cells - infection vs leukemia", "CBC"),
        FinalFeature("med.disseminated_intravascular_coagulation", "DIC", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Consumption coagulopathy - systemic activation", "Coags"),
        FinalFeature("med.sepsis", "Sepsis", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Life-threatening organ dysfunction", "SOFA, qSOFA"),
        FinalFeature("med.septic_shock", "Septic Shock", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Sepsis with hypotension requiring vasopressors", "Clinical"),
        FinalFeature("med.anaphylaxis", "Anaphylaxis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "IgE-mediated systemic reaction", "Clinical"),
        FinalFeature("med.angioedema", "Angioedema", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Swelling - allergic vs hereditary vs drug-induced", "Clinical"),
        FinalFeature("med.pulmonary_embolism", "Pulmonary Embolism", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "risk",
                    "PE - DVT migration to lungs", "CTPA, D-dimer"),
        FinalFeature("med.deep_vein_thrombosis", "DVT", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Blood clot in deep veins", "Ultrasound"),
        FinalFeature("med.pneumonia", "Pneumonia", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "severity",
                    "Community vs hospital acquired", "CXR, culture"),
        FinalFeature("med.tuberculosis", "Tuberculosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Mycobacterium tuberculosis infection", "Smear, culture, Xpert"),
        FinalFeature("med.malaria", "Malaria", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Plasmodium species - mosquito transmission", "Thick smear"),
        FinalFeature("med.hiv", "HIV", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "stage",
                    "Human immunodeficiency virus", "ELISA, viral load"),
        FinalFeature("med.hepatitis_b", "Hepatitis B", FinalSystem.ADDITIONAL_MEDICAL, (0, 6), "phase",
                    "Acute, chronic, carrier", "Serology"),
        FinalFeature("med.hepatitis_c", "Hepatitis C", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Chronic viral hepatitis", "RNA PCR"),
        FinalFeature("med.covid19", "COVID-19", FinalSystem.ADDITIONAL_MEDICAL, (0, 5), "severity",
                    "SARS-CoV-2 infection", "PCR, antigen"),
        FinalFeature("med.influenza", "Influenza", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Seasonal flu - types A and B", "Rapid test"),
        FinalFeature("med.zika", "Zika Virus", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Mosquito-borne - congenital syndrome", "PCR"),
        FinalFeature("med.ebola", "Ebola", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Viral hemorrhagic fever", "PCR"),
        FinalFeature("med.sars", "SARS", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "2002-2003 coronavirus outbreak", "PCR"),
        FinalFeature("mers", "MERS", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Middle East respiratory syndrome", "PCR"),
        FinalFeature("med.mononucleosis", "Infectious Mononucleosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "EBV - kissing disease", "Mono spot, EBV serology"),
        FinalFeature("med.lyme", "Lyme Disease", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "stage",
                    "Borrelia burgdorferi - tick-borne", "Clinical, serology"),
        FinalFeature("med.herpes_simplex", "Herpes Simplex", FinalSystem.ADDITIONAL_MEDICAL, (0, 2), "type",
                    "HSV-1 oral, HSV-2 genital", "PCR, culture"),
        FinalFeature("med.herpes_zoster", "Herpes Zoster", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Shingles - VZV reactivation", "Clinical"),
        FinalFeature("med.hpv", "Human Papillomavirus", FinalSystem.ADDITIONAL_MEDICAL, (0, 100), "types",
                    "200+ types - cervical cancer risk", "PCR typing"),
        FinalFeature("med.gonorrhea", "Gonorrhea", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Neisseria gonorrhoeae", "NAAT"),
        FinalFeature("med.chlamydia", "Chlamydia", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Chlamydia trachomatis", "NAAT"),
        FinalFeature("med.syphilis", "Syphilis", FinalSystem.ADDITIONAL_MEDICAL, (0, 4), "stage",
                    "Treponema pallidum - primary to tertiary", "RPR, FTA-ABS"),
        FinalFeature("med.trichomoniasis", "Trichomoniasis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Trichomonas vaginalis", "Wet mount"),
        FinalFeature("med.candidiasis", "Candidiasis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Yeast infection - Candida species", "KOH, culture"),
        FinalFeature("med.bacterial_vaginosis", "Bacterial Vaginosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Gardnerella - clue cells", "Wet mount"),
        FinalFeature("med.chancroid", "Chancroid", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "binary",
                    "Haemophilus ducreyi", "Culture"),
        FinalFeature("med.pediculosis", "Pediculosis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Lice - capitis, corporis, pubis", "Visualization"),
        FinalFeature("med.scabies", "Scabies", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Sarcoptes scabiei - mite infestation", "Skin scraping"),
        FinalFeature("med.cellulitis", "Cellulitis", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Skin and soft tissue infection", "Clinical"),
        FinalFeature("med.abscess", "Abscess", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Collection of pus - drained", "Clinical, ultrasound"),
        FinalFeature("med.impetigo", "Impetigo", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Superficial skin infection - bullous vs non-bullous", "Clinical"),
        FinalFeature("med.dermatitis", "Dermatitis", FinalSystem.ADDITIONAL_MEDICAL, (0, 10), "type",
                    "Atopic, contact, seborrheic, etc.", "Clinical"),
        FinalFeature("med.eczema", "Eczema", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Atopic dermatitis - pruritic rash", "Clinical"),
        FinalFeature("med.rosacea", "Rosacea", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "subtype",
                    "Facial erythema and papules", "Clinical"),
        FinalFeature("med.vitiligo", "Vitiligo", FinalSystem.ADDITIONAL_MEDICAL, (0, 1), "scale",
                    "Depigmented skin patches", "Clinical"),
        FinalFeature("med.alopecia", "Alopecia", FinalSystem.ADDITIONAL_MEDICAL, (0, 3), "type",
                    "Areata, androgenetic, traction", "Clinical"),
        
        # ============ PSYCHOLOGICAL DISORDERS (50 features) ============
        FinalFeature("psych.major_depressive", "Major Depressive Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "MDD - 5+ symptoms for 2+ weeks", "DSM-5 criteria"),
        FinalFeature("psych.persistent_depressive", "Persistent Depressive Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Dysthymia - chronic low mood 2+ years", "DSM-5"),
        FinalFeature("psych.bipolar_i", "Bipolar I Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Mania + depression - psychosis possible", "DSM-5"),
        FinalFeature("psych.bipolar_ii", "Bipolar II Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Hypomania + depression", "DSM-5"),
        FinalFeature("psych.cyclothymia", "Cyclothymia", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Chronic hypomanic and depressive symptoms", "DSM-5"),
        FinalFeature("psych.gad", "Generalized Anxiety Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Excessive worry 6+ months", "DSM-5"),
        FinalFeature("psych.panic_disorder", "Panic Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Recurrent unexpected panic attacks", "DSM-5"),
        FinalFeature("psych.social_anxiety", "Social Anxiety Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Social performance fear", "DSM-5"),
        FinalFeature("psych.specific_phobia", "Specific Phobia", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Marked fear of specific object/situation", "DSM-5"),
        FinalFeature("psych.ocd", "Obsessive-Compulsive Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Obsessions and compulsions - ego-dystonic", "DSM-5"),
        FinalFeature("psych.ptsd", "Post-Traumatic Stress Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Trauma re-experiencing, avoidance, hyperarousal", "DSM-5"),
        FinalFeature("psych.acute_stress", "Acute Stress Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Trauma symptoms <1 month", "DSM-5"),
        FinalFeature("psych.dissociative_identity", "Dissociative Identity Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Multiple identities - formerly MPD", "DSM-5"),
        FinalFeature("psych.depersonalization", "Depersonalization/Derealization", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Feeling detached from self/reality", "DSM-5"),
        FinalFeature("psych.somatic_symptom", "Somatic Symptom Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Excessive thoughts about somatic symptoms", "DSM-5"),
        FinalFeature("psych.illness_anxiety", "Illness Anxiety Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Fear of having serious illness", "DSM-5"),
        FinalFeature("psych.conversion", "Conversion Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Neurological symptoms without organic cause", "DSM-5"),
        FinalFeature("psych.factitious", "Factitious Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Minvented symptoms - primary gain", "DSM-5"),
        FinalFeature("psych.malingering", "Malingering", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "External motivation for symptoms", "DSM-5"),
        FinalFeature("psych.schizophrenia", "Schizophrenia", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Positive, negative, cognitive symptoms 6+ months", "DSM-5"),
        FinalFeature("psych.schizoaffective", "Schizoaffective Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Schizophrenia + mood episode", "DSM-5"),
        FinalFeature("psych.delusional", "Delusional Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Non-bizarre delusions without other symptoms", "DSM-5"),
        FinalFeature("psych.brief_psychotic", "Brief Psychotic Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Psychotic symptoms <1 month", "DSM-5"),
        FinalFeature("psych.schizophreniform", "Schizophreniform Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Schizophrenia 1-6 months", "DSM-5"),
        FinalFeature("psych.anorexia_nervosa", "Anorexia Nervosa", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Restriction, fear of gaining weight, body image", "DSM-5"),
        FinalFeature("psych.bulimia_nervosa", "Bulimia Nervosa", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Binge-purge cycle", "DSM-5"),
        FinalFeature("psych.binge_eating", "Binge Eating Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Binge without compensatory behaviors", "DSM-5"),
        FinalFeature("psych.arfid", "Avoidant/Restrictive Food Intake", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Feeding disturbance without body image concerns", "DSM-5"),
        FinalFeature("psych.insomnia_disorder", "Insomnia Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Difficulty sleeping 3+ months", "DSM-5"),
        FinalFeature("psych.hypersomnolence", "Hypersomnolence Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Excessive sleepiness 3+ months", "DSM-5"),
        FinalFeature("psych.narcolepsy", "Narcolepsy", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Sleep attacks, cataplexy, sleep paralysis", "Polysomnography"),
        FinalFeature("psych.sleep_apnea", "Sleep Apnea", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Obstructive - snoring, gasping", "Polysomnography"),
        FinalFeature("psych.restless_legs", "Restless Legs Syndrome", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Uncomfortable urge to move legs at rest", "Clinical"),
        FinalFeature("psych.circadian_rhythm", "Circadian Rhythm Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 3), "type",
                    "Sleep phase shift - delayed vs advanced", "Actigraphy"),
        FinalFeature("psych.adhd_combined", "ADHD Combined Type", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Inattentive + hyperactive-impulsive symptoms", "DSM-5"),
        FinalFeature("psych.adhd_inattentive", "ADHD Inattentive Type", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Mostly inattentive symptoms", "DSM-5"),
        FinalFeature("psych.adhd_hyperactive", "ADHD Hyperactive Type", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Mostly hyperactive-impulsive", "DSM-5"),
        FinalFeature("psych.autism_asd", "Autism Spectrum Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 3), "level",
                    "Social communication deficits, restricted behaviors", "DSM-5"),
        FinalFeature("psych.tourette", "Tourette Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Motor and vocal tics >1 year", "DSM-5"),
        FinalFeature("psych.transient_tic", "Transient Tic Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Tics <1 year", "DSM-5"),
        FinalFeature("psych.personalities_antisocial", "Antisocial Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Disregard for rights of others - conduct disorder + 18", "DSM-5"),
        FinalFeature("psych.personalities_borderline", "Borderline Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Instability in relationships, identity, affect", "DSM-5"),
        FinalFeature("personalities_narcissistic", "Narcissistic Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Grandiosity, need for admiration, lack of empathy", "DSM-5"),
        FinalFeature("psych.personalities_histionic", "Histrionic Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Excessive emotionality and attention-seeking", "DSM-5"),
        FinalFeature("personalities_dependent", "Dependent Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Submissive and reliant on others", "DSM-5"),
        FinalFeature("psych.personalities_avoidant", "Avoidant Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Social inhibition, fear of criticism", "DSM-5"),
        FinalFeature("psych.personalities_ocd", "Obsessive-Compulsive Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "Preoccupation with order and control", "DSM-5"),
        FinalFeature("psych.dissocial", "Dissocial Personality Disorder", FinalSystem.ADDITIONAL_PSYCH, (0, 1), "scale",
                    "ASPD equivalent in ICD", "ICD-10"),
        
        # ============ SOCIAL DETERMINANTS (50 features) ============
        FinalFeature("soc.income_level", "Income Level", FinalSystem.ADDITIONAL_SOCIAL, (0, 1000000), "currency",
                    "Annual household income", "Survey"),
        FinalFeature("soc.education_years", "Education Years", FinalSystem.ADDITIONAL_SOCIAL, (0, 25), "years",
                    "Years of formal schooling", "Survey"),
        FinalFeature("soc.employment_status", "Employment Status", FinalSystem.ADDITIONAL_SOCIAL, (0, 5), "status",
                    "Employed, unemployed, retired, etc.", "Survey"),
        FinalFeature("soc.occupation_class", "Occupation Class", FinalSystem.ADDITIONAL_SOCIAL, (0, 10), "class",
                    "White collar, blue collar, service", "Occupation"),
        FinalFeature("soc.marital_status", "Marital Status", FinalSystem.ADDITIONAL_SOCIAL, (0, 6), "status",
                    "Single, married, divorced, widowed, etc.", "Survey"),
        FinalFeature("soc.household_size", "Household Size", FinalSystem.ADDITIONAL_SOCIAL, (1, 20), "people",
                    "Number in household", "Census"),
        FinalFeature("soc.housing_ownership", "Housing Ownership", FinalSystem.ADDITIONAL_SOCIAL, (0, 1), "binary",
                    "Own vs rent", "Survey"),
        FinalFeature("soc.housing_quality", "Housing Quality", FinalSystem.ADDITIONAL_SOCIAL, (0, 10), "score",
                    "Condition and amenities", "Assessment"),
        FinalFeature("soc.neighborhood_safety", "Neighborhood Safety", FinalSystem.ADDITIONAL_SOCIAL, (0, 100), "%",
                    "Perceived safety", "Survey"),
        FinalFeature("soc.social_support_network", "Social Support Network", FinalSystem.ADDITIONAL_SOCIAL, (0, 50), "contacts",
                    "Number of close contacts", "Social network"),
        FinalFeature("soc.civic_engagement", "Civic Engagement", FinalSystem.ADDITIONAL_SOCIAL, (0, 10), "score",
                    "Voting, volunteering, community", "Survey"),
        FinalFeature("soc.food_security", "Food Security", FinalSystem.ADDITIONAL_SOCIAL, (0, 3), "level",
                    "USDA food security scale", "Survey"),
        FinalFeature("soc.access_healthcare", "Access to Healthcare", FinalSystem.ADDITIONAL_SOCIAL, (0, 1), "scale",
                    "Has usual source of care", "Survey"),
        FinalFeature("soc.health_insurance_status", "Health Insurance Status", FinalSystem.ADDITIONAL_SOCIAL, (0, 3), "type",
                    "Private, Medicare, Medicaid, none", "Survey"),
        FinalFeature("soc.technology_access", "Technology Access", FinalSystem.ADDITIONAL_SOCIAL, (0, 1), "scale",
                    "Internet and device access", "Survey"),
        FinalFeature("soc.transportation_access", "Transportation Access", FinalSystem.ADDITIONAL_SOCIAL, (0, 1), "scale",
                    "Reliable transportation for needs", "Survey"),
        FinalFeature("soc.discrimination_exposure", "Discrimination Exposure", FinalSystem.ADDITIONAL_SOCIAL, (0, 100), "frequency",
                    "Experienced discrimination", "Survey"),
        FinalFeature("soc.stress_life", "Life Stressors", FinalSystem.ADDITIONAL_SOCIAL, (0, 20), "count",
                    "Recent stressful life events", "Life events"),
        FinalFeature("soc.adverse_childhood", "Adverse Childhood Experiences", FinalSystem.ADDITIONAL_SOCIAL, (0, 10), "count",
                    "ACEs - abuse, neglect, household dysfunction", "Survey"),
        
        # ============ ADDITIONAL ENVIRONMENTAL (50 features) ============
        FinalFeature("env.indoor_air_quality", "Indoor Air Quality", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 100), "score",
                    "IAQ - VOC, PM, CO2", "Monitoring"),
        FinalFeature("env.mold_present", "Mold Presence", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 1), "binary",
                    "Visible or detected mold", "Inspection"),
        FinalFeature("env.lead_paint", "Lead Paint", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 1), "binary",
                    "Pre-1978 housing lead risk", "Testing"),
        FinalFeature("env.asbestos_present", "Asbestos Present", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 1), "binary",
                    "Building material containing asbestos", "Inspection"),
        FinalFeature("env.radon_level", "Radon Level", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 500), "pCi/L",
                    "Indoor radon concentration", "Testing"),
        FinalFeature("env.water_quality_home", "Home Water Quality", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 100), "score",
                    "Contaminant testing", "Lab testing"),
        FinalFeature("env.noise_home", "Home Noise Level", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 100), "dB",
                    "Indoor noise", "Meter"),
        FinalFeature("env.light_exposure", "Light Exposure", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 10000), "lux",
                    "Indoor lighting level", "Lux meter"),
        FinalFeature("env.green_space", "Green Space Access", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 1), "scale",
                    "Proximity to parks/nature", "GIS"),
        FinalFeature("env.walkability", "Walkability Score", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 100), "score",
                    "Walkable neighborhood features", "Walk score"),
        FinalFeature("env.pollution_index", "Pollution Index", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 500), "AQI",
                    "Local air quality", "EPA"),
        FinalFeature("env.uv_exposure_daily", "Daily UV Exposure", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 20), "UV index",
                    "Sun protection needed", "UV index"),
        FinalFeature("env.temperature_home", "Home Temperature", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (10, 35), "°C",
                    "Indoor thermostat setting", "Thermostat"),
        FinalFeature("env.humidity_home", "Home Humidity", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (20, 80), "%",
                    "Indoor relative humidity", "Hygrometer"),
        FinalFeature("env.ergonomics_workstation", "Workstation Ergonomics", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 100), "score",
                    "Chair, desk, monitor setup", "Assessment"),
        FinalFeature("env.screen_time", "Screen Time", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 24), "hours/day",
                    "Daily screen exposure", "Self-report"),
        FinalFeature("env.night_light_exposure", "Night Light Exposure", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 100), "lux",
                    "Evening blue light", "Meter"),
        FinalFeature("env.crowding", "Housing Crowding", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 10), "persons/room",
                    "People per room ratio", "Census"),
        FinalFeature("env.homelessness", "Homelessness Status", FinalSystem.ADDITIONAL_ENVIRONMENTAL, (0, 2), "type",
                    "Street, shelter, couch-surfing", "Status"),
        
        # ============ TECHNOLOGY USE (50 features) ============
        FinalFeature("tech.smartphone_use", "Smartphone Use", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 24), "hours/day",
                    "Daily screen time", "Screen time app"),
        FinalFeature("tech.social_media_use", "Social Media Use", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 12), "hours/day",
                    "Platform engagement time", "Self-report"),
        FinalFeature("tech.gaming_time", "Gaming Time", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 12), "hours/day",
                    "Video game playing", "Self-report"),
        FinalFeature("tech.streaming_time", "Streaming Time", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 12), "hours/day",
                    "Video streaming consumption", "Self-report"),
        FinalFeature("tech.email_frequency", "Email Frequency", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 200), "emails/day",
                    "Work and personal email", "Client data"),
        FinalFeature("tech.video_conferencing", "Video Conferencing", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 8), "hours/day",
                    "Zoom, Teams, etc.", "Self-report"),
        FinalFeature("tech.online_shopping", "Online Shopping", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 100), "purchases/month",
                    "E-commerce transactions", "Transaction data"),
        FinalFeature("tech.digital_literacy", "Digital Literacy", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 100), "score",
                    "Technology skill level", "Assessment"),
        FinalFeature("tech.privacy_settings", "Privacy Settings Awareness", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 1), "scale",
                    "Social media privacy management", "Self-report"),
        FinalFeature("tech.cybersecurity_hygiene", "Cybersecurity Hygiene", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 10), "score",
                    "Password, 2FA, updates", "Assessment"),
        FinalFeature("tech.smart_home_devices", "Smart Home Devices", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 50), "count",
                    "IoT devices in home", "Survey"),
        FinalFeature("tech.wearable_use", "Wearable Device Use", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 1), "binary",
                    "Fitness tracker, smartwatch", "Survey"),
        FinalFeature("tech.health_app_use", "Health App Use", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 20), "apps",
                    "Health tracking applications", "Survey"),
        FinalFeature("tech.telemedicine_use", "Telemedicine Use", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 12), "visits/year",
                    "Virtual healthcare visits", "Records"),
        FinalFeature("tech.online_education", "Online Learning", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 20), "hours/month",
                    "MOOCs, courses online", "Survey"),
        FinalFeature("tech.cryptocurrency_ownership", "Cryptocurrency Ownership", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 1), "binary",
                    "Bitcoin, Ethereum, etc.", "Survey"),
        FinalFeature("tech.nft_ownership", "NFT Ownership", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 100), "count",
                    "Digital collectibles", "Wallet"),
        FinalFeature("tech.automation_home", "Home Automation", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 10), "score",
                    "Smart lighting, thermostat, security", "Survey"),
        FinalFeature("tech.electric_vehicle", "Electric Vehicle Ownership", FinalSystem.ADDITIONAL_TECHNOLOGY, (0, 1), "binary",
                    "EV or hybrid vehicle", "Survey"),
        
        # ============ LEGAL STATUS (50 features) ============
        FinalFeature("legal.citizenship", "Citizenship Status", FinalSystem.ADDITIONAL_LEGAL, (0, 5), "type",
                    "Citizen, permanent resident, visa, undocumented", "Immigration"),
        FinalFeature("legal.drivers_license", "Driver's License Status", FinalSystem.ADDITIONAL_LEGAL, (0, 3), "type",
                    "Valid, suspended, expired, none", "DMV"),
        FinalFeature("legal.legal_residency", "Legal Residency Status", FinalSystem.ADDITIONAL_LEGAL, (0, 5), "type",
                    "Green card, visa type, citizenship", "Immigration"),
        FinalFeature("legal.visa_type", "Visa Type", FinalSystem.ADDITIONAL_LEGAL, (0, 20), "type",
                    "Tourist, work, student, etc.", "Immigration"),
        FinalFeature("legal.arrest_history", "Arrest History", FinalSystem.ADDITIONAL_LEGAL, (0, 50), "count",
                    "Number of arrests", "Record"),
        FinalFeature("legal.conviction_history", "Conviction History", FinalSystem.ADDITIONAL_LEGAL, (0, 20), "count",
                    "Criminal convictions", "Record"),
        FinalFeature("legal.incarceration_history", "Incarceration History", FinalSystem.ADDITIONAL_LEGAL, (0, 10), "years",
                    "Time in prison", "Record"),
        FinalFeature("legal.parole_status", "Parole Status", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "scale",
                    "Currently on parole", "Record"),
        FinalFeature("legal.probation_status", "Probation Status", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "scale",
                    "Currently on probation", "Record"),
        FinalFeature("legal.restraining_order", "Restraining Order", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "binary",
                    "Active restraining order", "Court"),
        FinalFeature("legal.child_support", "Child Support Obligation", FinalSystem.ADDITIONAL_LEGAL, (0, 10000), "monthly",
                    "Monthly child support amount", "Court order"),
        FinalFeature("legal.alimony", "Alimony/Spousal Support", FinalSystem.ADDITIONAL_LEGAL, (0, 10000), "monthly",
                    "Monthly support amount", "Court order"),
        FinalFeature("legal.bankruptcy", "Bankruptcy Status", FinalSystem.ADDITIONAL_LEGAL, (0, 7), "years",
                    "Time since bankruptcy", "Court record"),
        FinalFeature("legal.lien", "Tax Lien", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "binary",
                    "Outstanding tax lien", "IRS"),
        FinalFeature("legal.judgment", "Civil Judgment", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "binary",
                    "Outstanding civil judgment", "Court"),
        FinalFeature("legal.license_professional", "Professional License", FinalSystem.ADDITIONAL_LEGAL, (0, 10), "count",
                    "Number of professional licenses", "License board"),
        FinalFeature("legal.cdl", "Commercial Driver's License", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "binary",
                    "CDL status and endorsements", "DMV"),
        FinalFeature("legal.pilot_license", "Pilot License", FinalSystem.ADDITIONAL_LEGAL, (0, 5), "type",
                    "Private, commercial, ATP", "FAA"),
        FinalFeature("legal.firearms_license", "Firearms License", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "binary",
                    "Concealed carry permit", "Permit"),
        FinalFeature("legal.business_license", "Business License", FinalSystem.ADDITIONAL_LEGAL, (0, 1), "binary",
                    "Business operation license", "Local"),


        # ============ SPIRITUAL/RELIGIOUS (50 features) ============
        FinalFeature("spirit.religion", "Religion", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 20), "type",
                    "Christianity, Islam, Hinduism, etc.", "Self-report"),
        FinalFeature("spirit.religiosity", "Religiosity", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Importance of religion in life", "Scale"),
        FinalFeature("spirit.church_attendance", "Church Attendance", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 7), "times/month",
                    "Religious service attendance", "Survey"),
        FinalFeature("spirit.prayer_frequency", "Prayer Frequency", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 50), "times/week",
                    "Personal prayer", "Survey"),
        FinalFeature("spirit.spiritual_beliefs", "Spiritual Beliefs", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Belief in higher power or transcendence", "Survey"),
        FinalFeature("spirit.meditation_practice", "Meditation Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 7), "times/week",
                    "Meditation or mindfulness", "Survey"),
        FinalFeature("spirit.buddhism_practice", "Buddhism Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Buddhist practice level", "Survey"),
        FinalFeature("spirit.yoga_practice", "Yoga Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 7), "times/week",
                    "Yoga sessions", "Survey"),
        FinalFeature("spirit.fasting_practice", "Fasting Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Religious or spiritual fasting", "Survey"),
        FinalFeature("spirit.pilgrimage", "Pilgrimage", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Religious pilgrimage completed", "Survey"),
        FinalFeature("spirit.charity_giving", "Charity Giving", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 50), "% income",
                    "Religious or charitable giving", "Survey"),
        FinalFeature("spirit.religious_exploration", "Religious Exploration", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Exploring different faiths", "Survey"),
        FinalFeature("spirit.atheism", "Atheism/Agnosticism", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Non-belief level", "Survey"),
        FinalFeature("spirit.new_age_beliefs", "New Age Beliefs", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Astrology, crystals, etc.", "Survey"),
        FinalFeature("spirit.shamanism", "Shamanic Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Traditional or neo-shamanic practices", "Survey"),
        FinalFeature("spirit.wicca", "Wiccan/Pagan Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Wiccan or pagan tradition", "Survey"),
        FinalFeature("spirit.mormon_practice", "LDS Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 1), "scale",
                    "Mormon observance level", "Survey"),
        FinalFeature("spirit.jewish_observance", "Jewish Observance", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 5), "level",
                    "Orthodox to Reform", "Survey"),
        FinalFeature("spirit.muslim_observance", "Muslim Observance", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 5), "level",
                    "Secular to devout", "Survey"),
        FinalFeature("spirit.hindu_practice", "Hindu Practice", FinalSystem.ADDITIONAL_SPIRITUAL, (0, 5), "level",
                    "Hindu observance", "Survey"),

        # ============ ARTS & CREATIVITY (50 features) ============
        FinalFeature("art.music_training", "Music Training", FinalSystem.ADDITIONAL_ARTS, (0, 20), "years",
                    "Years of instrument or vocal training", "History"),
        FinalFeature("art.instrument_playing", "Instrument Playing", FinalSystem.ADDITIONAL_ARTS, (0, 10), "instruments",
                    "Number of instruments played", "Self-report"),
        FinalFeature("art.singing", "Singing Ability", FinalSystem.ADDITIONAL_ARTS, (0, 10), "level",
                    "Vocal skill level", "Assessment"),
        FinalFeature("art.drawing", "Drawing Skill", FinalSystem.ADDITIONAL_ARTS, (0, 10), "level",
                    "Drawing ability", "Portfolio"),
        FinalFeature("art.painting", "Painting Skill", FinalSystem.ADDITIONAL_ARTS, (0, 10), "level",
                    "Painting ability", "Portfolio"),
        FinalFeature("art.sculpture", "Sculpture", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Sculpting practice", "Portfolio"),
        FinalFeature("art.photography", "Photography", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Photography hobby or profession", "Portfolio"),
        FinalFeature("art.writing", "Writing", FinalSystem.ADDITIONAL_ARTS, (0, 10), "level",
                    "Creative writing ability", "Portfolio"),
        FinalFeature("art.poetry", "Poetry", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Poetry writing", "Portfolio"),
        FinalFeature("art.dance", "Dance", FinalSystem.ADDITIONAL_ARTS, (0, 10), "level",
                    "Dance training or performance", "History"),
        FinalFeature("art.theater", "Theater", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Acting or theater involvement", "Experience"),
        FinalFeature("art.cinema_appreciation", "Cinema Appreciation", FinalSystem.ADDITIONAL_ARTS, (0, 10), "level",
                    "Film knowledge and appreciation", "Survey"),
        FinalFeature("art.literature_reading", "Literature Reading", FinalSystem.ADDITIONAL_ARTS, (0, 100), "books/year",
                    "Annual reading volume", "Survey"),
        FinalFeature("art.gallery_visits", "Gallery Visits", FinalSystem.ADDITIONAL_ARTS, (0, 50), "visits/year",
                    "Museum and gallery attendance", "Survey"),
        FinalFeature("art.concert_attendance", "Concert Attendance", FinalSystem.ADDITIONAL_ARTS, (0, 50), "concerts/year",
                    "Live music events", "Survey"),
        FinalFeature("art.creative_digital", "Digital Art Creation", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Digital illustration, animation", "Portfolio"),
        FinalFeature("art.craft_knitting", "Knitting/Crocheting", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Fiber arts", "Projects"),
        FinalFeature("art.woodworking", "Woodworking", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Woodworking projects", "Portfolio"),
        FinalFeature("art.ceramics", "Ceramics", FinalSystem.ADDITIONAL_ARTS, (0, 1), "scale",
                    "Pottery and ceramics", "Portfolio"),
        
        # ============ LANGUAGE (50 features) ============
        FinalFeature("lang.native_language", "Native Language", FinalSystem.ADDITIONAL_LANGUAGE, (0, 100), "language",
                    "First language", "Survey"),
        FinalFeature("lang.languages_spoken", "Languages Spoken", FinalSystem.ADDITIONAL_LANGUAGE, (0, 20), "count",
                    "Number of languages", "Survey"),
        FinalFeature("lang.english_fluency", "English Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "English proficiency", "Self-assessment"),
        FinalFeature("lang.spanish_fluency", "Spanish Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Spanish proficiency", "Self-assessment"),
        FinalFeature("lang.mandarin_fluency", "Mandarin Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Chinese proficiency", "Self-assessment"),
        FinalFeature("lang.french_fluency", "French Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "French proficiency", "Self-assessment"),
        FinalFeature("lang.german_fluency", "German Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "German proficiency", "Self-assessment"),
        FinalFeature("lang.japanese_fluency", "Japanese Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Japanese proficiency", "Self-assessment"),
        FinalFeature("lang.korean_fluency", "Korean Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Korean proficiency", "Self-assessment"),
        FinalFeature("lang.arabic_fluency", "Arabic Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Arabic proficiency", "Self-assessment"),
        FinalFeature("lang.hindi_fluency", "Hindi Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Hindi proficiency", "Self-assessment"),
        FinalFeature("lang.portuguese_fluency", "Portuguese Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Portuguese proficiency", "Self-assessment"),
        FinalFeature("lang.italian_fluency", "Italian Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Italian proficiency", "Self-assessment"),
        FinalFeature("lang.russian_fluency", "Russian Fluency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "Russian proficiency", "Self-assessment"),
        FinalFeature("lang.reading_proficiency", "Reading Proficiency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 10), "level",
                    "Literacy level", "Assessment"),
        FinalFeature("lang.writing_proficiency", "Writing Proficiency", FinalSystem.ADDITIONAL_LANGUAGE, (0, 10), "level",
                    "Written expression", "Assessment"),
        FinalFeature("lang.oral_comprehension", "Oral Comprehension", FinalSystem.ADDITIONAL_LANGUAGE, (0, 10), "level",
                    "Listening comprehension", "Assessment"),
        FinalFeature("lang.oral_expression", "Oral Expression", FinalSystem.ADDITIONAL_LANGUAGE, (0, 10), "level",
                    "Speaking ability", "Assessment"),
        FinalFeature("lang.sign_language", "Sign Language", FinalSystem.ADDITIONAL_LANGUAGE, (0, 5), "level",
                    "ASL or other sign proficiency", "Assessment"),
    ]
    
    for f in features:
        if hasattr(f, 'feature_id'):
            FINAL_FEATURES[f.feature_id] = f


_register_final_features()


def get_final_feature(feature_id: str) -> FinalFeature:
    return FINAL_FEATURES.get(feature_id)


def get_final_feature_count() -> int:
    return len(FINAL_FEATURES)


def get_total_all_features() -> int:
    """Total features across all modules."""
    from ontology import (
        get_feature_count, get_cognitive_feature_count,
        get_psychological_feature_count, get_social_feature_count,
        get_economic_feature_count, get_political_feature_count,
        get_remaining_feature_count
    )
    total = 0
    try:
        total += get_feature_count()
    except Exception:
        total += 175
    try:
        total += get_cognitive_feature_count()
    except Exception:
        pass
    try:
        total += get_psychological_feature_count()
    except Exception:
        pass
    try:
        total += get_social_feature_count()
    except Exception:
        pass
    try:
        total += get_economic_feature_count()
    except Exception:
        pass
    try:
        total += get_political_feature_count()
    except Exception:
        pass
    try:
        total += get_remaining_feature_count()
    except Exception:
        pass
    total += get_final_feature_count()
    return total


# Need to add the LegalSystem class that was referenced
class LegalSystem(Enum):
    ADDITIONAL_LEGAL = auto()


# And a simple dataclass for Legal features
@dataclass
class LegalFeature:
    feature_id: str
    feature_name: str
    system: LegalSystem
    normal_range: tuple
    unit: str
    description: str
    measurement: str
    tags: List[str] = field(default_factory=list)