"""
Missing Feature Registry — Final Sections AF-AY
===============================================
Missing features from the original specification that need to be added.
"""

from dataclasses import dataclass, field
from typing import List
from enum import Enum, auto


class MissingSystem(Enum):
    NUTRITIONAL_EXTENDED = auto()
    IMMUNOLOGICAL_EXTENDED = auto()
    NEUROLOGICAL_EXTENDED = auto()
    ENDOCRINE_EXTENDED = auto()
    SLEEP_EXTENDED = auto()
    PAIN_SYSTEM = auto()
    DEATH_SYSTEM = auto()
    HERITAGE_SYSTEM = auto()
    DIPLOMATIC_EXTENDED = auto()
    INTELLIGENCE_SYSTEM = auto()
    PROPAGANDA_SYSTEM = auto()
    TRADE_SYSTEM = auto()
    CURRENCY_SYSTEM = auto()
    LABOR_SYSTEM = auto()
    HOUSING_SYSTEM = auto()
    MEDICINE_EXTENDED = auto()
    MUSIC_SYSTEM = auto()
    SMELL_SYSTEM = auto()
    ARCHITECTURAL_EXTENDED = auto()


@dataclass
class MissingFeature:
    feature_id: str
    feature_name: str
    system: MissingSystem
    normal_range: tuple
    unit: str
    description: str
    measurement: str
    tags: List[str] = field(default_factory=list)


MISSING_FEATURES: dict = {}


def _register_missing_features():
    global MISSING_FEATURES
    
    features = [
        # ============ AF: NUTRITIONAL & METABOLIC (25 features) ============
        MissingFeature("nutrext.macronutrient_ratio", "Macronutrient Ratio", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 100), "%", "Carb/fat/protein balance - ketogenic, Mediterranean",
                        "Food diary"),
        MissingFeature("nutrext.micronutrient_adequacy", "Micronutrient Adequacy", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 100), "%", "Vitamin and mineral intake - deficiency diseases",
                        "Blood test"),
        MissingFeature("nutrext.fiber_intake", "Fiber Intake", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 50), "g/day", "Gut microbiome fuel - 25-30g/day recommendation",
                        "Food record"),
        MissingFeature("nutrext.omega_ratio", "Omega-3/Omega-6 Ratio", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 20), "ratio", "Inflammation modulation - modern diet imbalance",
                        "Blood test"),
        MissingFeature("nutrext.antioxidant_capacity", "Antioxidant Capacity", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 10000), "ORAC", "Oxidative stress reduction - debated efficacy",
                        "ORAC assay"),
        MissingFeature("nutrext.glycemic_index", "Glycemic Index", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 100), "value", "Blood glucose rise speed - diabetes management",
                        "GI tables"),
        MissingFeature("nutrext.food_security", "Food Security Status", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 3), "level", "Marginal, low, very low - USDA classification",
                        "Survey"),
        MissingFeature("nutrext.famine_coping", "Famine Coping Strategy", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 5), "type", "Dietary diversification, wild food, migration, asset sale",
                        "Study"),
        MissingFeature("nutrext.nutritional_transition", "Nutritional Transition", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1), "scale", "Undernutrition to overnutrition - obesity epidemic",
                        "Epidemiology"),
        MissingFeature("nutrext.food_taboos", "Food Taboo Adherence", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1), "scale", "Religious, cultural, medical - pork, beef, shellfish",
                        "Cultural"),
        MissingFeature("nutrext.meal_timing", "Meal Timing Pattern", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 5), "type", "Breakfast, intermittent fasting - circadian alignment",
                        "Dietary"),
        MissingFeature("nutrext.cooking_method", "Cooking Method Effect", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 10), "type", "Raw, boiled, roasted, fermented - nutrient bioavailability",
                        "Cooking"),
        MissingFeature("nutrext.food_preservation", "Food Preservation Technique", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 10), "type", "Salting, smoking, drying, pickling, canning, refrigeration",
                        "Preservation"),
        MissingFeature("nutrext.spice_trade", "Spice Trade Value", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1000000), "historical", "Pepper, cinnamon, cloves - preservation and status",
                        "History"),
        MissingFeature("nutrext.caffeine_consumption", "Caffeine Consumption", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1000), "mg/day", "Alertness, dependence, withdrawal headache",
                        "Survey"),
        MissingFeature("nutrext.hydration_balance", "Hydration Balance", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 5), "L/day", "Water intake vs loss - euvolemia",
                        "Fluid balance"),
        MissingFeature("nutrext.electrolyte_balance", "Electrolyte Balance", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1), "scale", "Na, K, Mg, Ca equilibrium",
                        "Blood test"),
        MissingFeature("nutrext.acid_base_nutrition", "Acid-Base Nutrition", MissingSystem.NUTRITIONAL_EXTENDED,
                        (-50, 50), "mEq", "PRAL - potential renal acid load of diet",
                        "Calculation"),
        MissingFeature("nutrext.food_additive_exposure", "Food Additive Exposure", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 100), "additives", "Preservatives, colorings, flavorings",
                        "Consumption"),
        MissingFeature("nutrext.heavy_metal_intake", "Heavy Metal Intake", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 100), "µg/day", "Lead, cadmium, mercury from food",
                        "Biomonitoring"),
        MissingFeature("nutrext.mycotoxin_exposure", "Mycotoxin Exposure", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1), "scale", "Aflatoxin from moldy grain, nuts",
                        "Food testing"),
        MissingFeature("nutrext.pesticide_residue", "Pesticide Residue", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 100), " µg/kg", "On fruits and vegetables",
                        "Testing"),
        MissingFeature("nutrext.gmo_acceptance", "GMO Acceptance", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1), "scale", "Genetic modification acceptance",
                        "Survey"),
        MissingFeature("nutrext.organic_preference", "Organic Food Preference", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 1), "scale", "Willingness to pay premium for organic",
                        "Survey"),
        MissingFeature("nutrext.food_waste", "Food Waste", MissingSystem.NUTRITIONAL_EXTENDED,
                        (0, 50), "%", "Percentage of food discarded",
                        "Waste audit"),


        # ============ AG: IMMUNOLOGICAL & DEFENSIVE (25 features) ============
        MissingFeature("immdef.skin_barrier", "Skin Barrier Function", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 100), "%", "Physical and chemical - pH 4.5-5.5 acidic mantle",
                        "TEWL"),
        MissingFeature("immdef.mucus_layer", "Mucus Layer Thickness", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 10), "mm", "Respiratory and GI - trapping and clearance",
                        "Biopsy"),
        MissingFeature("immdef.ciliary_beat", "Ciliary Beat Frequency", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (12, 15), "Hz", "Mucociliary escalator - 12-15 Hz",
                        "High-speed camera"),
        MissingFeature("immdef.lysozyme", "Lysozyme Concentration", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 10), "mg/L", "Tears, saliva, mucus - bacterial cell wall lysis",
                        "Assay"),
        MissingFeature("immdef.defensin", "Defensin Production", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 100), "µg/mL", "Antimicrobial peptides - innate immunity",
                        "ELISA"),
        MissingFeature("immdef.interferon_response", "Interferon Response", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "Antiviral state induction - type I, II, III",
                        "Gene expression"),
        MissingFeature("immdef.inflammatory_reflex", "Inflammatory Reflex", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "Vagus nerve cholinergic anti-inflammatory pathway",
                        "Studies"),
        MissingFeature("immdef.sickness_behavior", "Sickness Behavior", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "Anorexia, lethargy, social withdrawal - adaptive",
                        "Behavioral"),
        MissingFeature("immdef.fever_benefit", "Fever Benefit Threshold", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (38, 40), "°C", "38-40°C enhances immune function - >40°C harmful",
                        "Clinical"),
        MissingFeature("immdef.leukocytosis_response", "Leukocytosis Response", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (4, 20), "×10⁹/L", "White blood cell increase - infection marker",
                        "CBC"),
        MissingFeature("immdef.acute_phase", "Acute Phase Proteins", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 100), "mg/L", "CRP, ferritin - inflammation nonspecific markers",
                        "Blood test"),
        MissingFeature("immdef.anaphylaxis_threshold", "Anaphylaxis Threshold", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "IgE-mediated - epinephrine requirement",
                        "Allergy test"),
        MissingFeature("immdef.autoimmune_flare", "Autoimmune Flare Trigger", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "Stress, infection, pregnancy - relapse pattern",
                        "Clinical"),
        MissingFeature("immdef.immunodeficiency", "Immunodeficiency Severity", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 5), "severity", "SCID severe vs IgA deficiency mild",
                        "Testing"),
        MissingFeature("immdef.graft_rejection", "Graft Rejection Type", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 3), "type", "Hyperacute, acute, chronic - matching and immunosuppression",
                        "Biopsy"),
        MissingFeature("immdef.cytokine_storm", "Cytokine Storm Risk", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "Excessive immune response - COVID, cytokine release syndrome",
                        "IL-6 level"),
        MissingFeature("immdef.tolerance_induction", "Tolerance Induction", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "Allergen immunotherapy success",
                        "Challenge test"),
        MissingFeature("immdef.vaccine_boost_response", "Vaccine Boost Response", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 10), "fold", "Antibody titer increase after booster",
                        "Titer"),
        MissingFeature("immdef.maternal_immunity", "Maternal Immunity Transfer", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "IgG transfer across placenta - neonatal protection",
                        "Cord blood"),
        MissingFeature("immdef.lactation_immunity", "Lactation Immunity", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 1), "scale", "Secretory IgA in breast milk",
                        "Milk analysis"),
        MissingFeature("immdef.mucosal_immunity", "Mucosal Immunity", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 100), "%", "Gut-associated lymphoid tissue - secretory IgA",
                        "Biopsy"),
        MissingFeature("immdef.complement_system", "Complement System", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 100), "%", "C3, C4 - opsonization and lysis",
                        "Assay"),
        MissingFeature("immdef.nk_cell_activity", "NK Cell Activity", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 100), "%", "Innate killing - tumor and virus surveillance",
                        "51Cr release"),
        MissingFeature("immdef.t_cell_memory", "T-Cell Memory", MissingSystem.IMMUNOLOGICAL_EXTENDED,
                        (0, 100), "%", "Central and effector memory T cells",
                        "Flow cytometry"),


        # ============ AH: NEUROLOGICAL & PSYCHIATRIC (25 features) ============
        MissingFeature("neuro.amyloid_cascade", "Alzheimer's Amyloid Cascade", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 100), "pg/mL", "Plaques and tangles - early vs late onset",
                        "CSF biomarker"),
        MissingFeature("neuro.dopamine_depletion", "Parkinson's Dopamine Depletion", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 80), "%", "Substantia nigra - Lewy bodies",
                        "DAT scan"),
        MissingFeature("neuro.cag_repeat", "Huntington's CAG Repeat", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (36, 120), "repeats", "Chorea, dementia, psychiatric - anticipation",
                        "Genetic test"),
        MissingFeature("neuro.als_motor_neuron", "ALS Motor Neuron Death", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "Upper and lower - 3-5 year survival",
                        "EMG"),
        MissingFeature("neuro.ms_relapse", "Multiple Sclerosis Relapse", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "Demyelination plaques - RRMS, SPMS, PPMS",
                        "MRI"),
        MissingFeature("neuro.seizure_type", "Epilepsy Seizure Type", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 5), "type", "Focal, generalized, unknown - 30% medication resistant",
                        "EEG"),
        MissingFeature("neuro.migraine_aura", "Migraine Aura", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "Visual, sensory, speech - cortical spreading depression",
                        "Clinical"),
        MissingFeature("neuro.ischemic_core", "Stroke Ischemic Core", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 100), "mL", "Irreversible damage - penumbra salvageable with rapid treatment",
                        "CT perfusion"),
        MissingFeature("neuro.aneurysm_risk", "Aneurysm Rupture Risk", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 10), "mm", "Size and location - 5-10mm annual rupture rate",
                        "MRA/CTA"),
        MissingFeature("neuro.tbi_grade", "Traumatic Brain Injury Grade", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 3), "grade", "Mild concussion, moderate, severe - CTE chronic",
                        "Clinical"),
        MissingFeature("neuro.schizophrenia_dim", "Schizophrenia Symptom Dimension", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 3), "type", "Positive, negative, cognitive - heterogeneity",
                        "PANSS"),
        MissingFeature("neuro.bipolar_episode", "Bipolar Mood Episode", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 4), "type", "Manic, hypomanic, depressive, mixed - cycling frequency",
                        "Clinical"),
        MissingFeature("neuro.borderline_emotion", "Borderline Emotional Dysregulation", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "Rapid mood shifts - rejection sensitivity",
                        "Clinical"),
        MissingFeature("neuro.ocd_intrusive", "OCD Intrusive Thought", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "Ego-dystonic - compulsion temporary relief",
                        "Y-BOCS"),
        MissingFeature("neuro.ptsd_trauma", "PTSD Trauma Memory", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "Re-experiencing, avoidance, hyperarousal, negative cognition",
                        "PCL-5"),
        MissingFeature("neuro.huntingtons_early", "Huntington's Early Markers", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "Premanifest - CAG carrier before symptoms",
                        "Biomarkers"),
        MissingFeature("neuro.parkinson_early", "Parkinson's Early Markers", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 1), "scale", "REM sleep behavior disorder, hyposmia - prodromal",
                        "Clinical"),
        MissingFeature("neuro.ms_lesion_load", "MS Lesion Load", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 100), "lesions", "T2 hyperintense lesions on MRI",
                        "MRI"),
        MissingFeature("neuro.epilepsy_syndrome", "Epilepsy Syndrome", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 20), "type", "Lennox-Gastaut, Dravet, Juvenile Myoclonic",
                        "Clinical"),
        MissingFeature("neuro.meningitis_cause", "Meningitis Cause", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 5), "type", "Bacterial, viral, fungal, TB",
                        "CSF analysis"),
        MissingFeature("neuro.encephalitis_etiology", "Encephalitis Etiology", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 10), "type", "Autoimmune, viral, paraneoplastic",
                        "Testing"),
        MissingFeature("neuro.neuropathy_type", "Neuropathy Type", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 10), "type", "Axonal, demyelinating, small fiber",
                        "NCS/EMG"),
        MissingFeature("neuro.myopathy_type", "Myopathy Type", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 10), "type", "Inflammatory, metabolic, muscular dystrophy",
                        "Biopsy"),
        MissingFeature("neuro.hydrocephalus_type", "Hydrocephalus Type", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 3), "type", "Communicating, non-communicating, normal pressure",
                        "Imaging"),
        MissingFeature("neuro.dementia_type", "Dementia Type", MissingSystem.NEUROLOGICAL_EXTENDED,
                        (0, 10), "type", "Alzheimer's, vascular, Lewy body, frontotemporal",
                        "Clinical"),


        # ============ AJ: SLEEP EXTENDED (20 features) ============
        MissingFeature("sleep.stages_architecture", "Sleep Stages Architecture", MissingSystem.SLEEP_EXTENDED,
                        (0, 100), "%", "N1/N2/N3/REM distribution",
                        "Polysomnography"),
        MissingFeature("sleep.circadian_amplitude", "Circadian Amplitude", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "Strength of circadian rhythm",
                        "Melatonin rhythm"),
        MissingFeature("sleep.sleep_pressure", "Sleep Pressure", MissingSystem.SLEEP_EXTENDED,
                        (0, 100), "%", "Homeostatic sleep drive",
                        "Sleep latency"),
        MissingFeature("sleep REM_atonia", "REM At Loss", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "REM sleep without atonia - RBD",
                        "Polysomnography"),
        MissingFeature("sleep.sleep_terrors", "Sleep Terrors", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "N3 confusional arousals - children",
                        "Clinical"),
        MissingFeature("sleep.somnambulism", "Somnambulism", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "Sleepwalking - N3 parasomnia",
                        "History"),
        MissingFeature("sleep.sleep_talking", "Sleep Talking", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "Somniloquy - NREM or REM",
                        "Bed partner"),
        MissingFeature("sleep.bruxism", "Bruxism", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "Teeth grinding during sleep",
                        "Dental exam"),
        MissingFeature("sleep.enuresis", "Nocturnal Enuresis", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "Bedwetting beyond age 5",
                        "Clinical"),
        MissingFeature("sleep.snoring_severity", "Snoring Severity", MissingSystem.SLEEP_EXTENDED,
                        (0, 10), "score", "Partner reported - OSA indicator",
                        "Survey"),
        MissingFeature("sleep.sleep_territory", "Sleep Environment", MissingSystem.SLEEP_EXTENDED,
                        (0, 1), "scale", "Bed sharing vs solo - partner disturbance",
                        "History"),
        MissingFeature("sleep.mattress_quality", "Mattress Quality", MissingSystem.SLEEP_EXTENDED,
                        (0, 10), "rating", "Support and comfort for sleep",
                        "Assessment"),
        MissingFeature("sleep.light_exposure_evening", "Evening Light Exposure", MissingSystem.SLEEP_EXTENDED,
                        (0, 1000), "lux", "Blue light before bed - circadian disruption",
                        "Meter"),
        MissingFeature("sleep.temperature_bedroom", "Bedroom Temperature", MissingSystem.SLEEP_EXTENDED,
                        (15, 30), "°C", "Optimal 18-20°C for sleep",
                        "Thermostat"),
        MissingFeature("sleep.noise_bedroom", "Bedroom Noise", MissingSystem.SLEEP_EXTENDED,
                        (0, 80), "dB", "Environmental noise during sleep",
                        "Meter"),
        MissingFeature("sleep.cortisol_night", "Nighttime Cortisol", MissingSystem.SLEEP_EXTENDED,
                        (0, 50), "nmol/L", "Should be low at night - disruption in stress",
                        "Saliva"),
        MissingFeature("sleep.gh_night", "Growth Hormone Night", MissingSystem.SLEEP_EXTENDED,
                        (0, 50), "mIU/L", "Secreted during deep sleep",
                        "Blood test"),
        MissingFeature("sleep.melatonin_onset", "Melatonin Onset", MissingSystem.SLEEP_EXTENDED,
                        (18, 24), "hour", "DLMO - dim light melatonin onset",
                        "Saliva"),
        MissingFeature("sleep.adenotonsillar_hypertrophy", "Adenotonsillar Hypertrophy", MissingSystem.SLEEP_EXTENDED,
                        (0, 3), "grade", "Pediatric OSA cause - examination",
                        "ENT exam"),
        MissingFeature("sleep.cpap_adherence", "CPAP Adherence", MissingSystem.SLEEP_EXTENDED,
                        (0, 8), "hours/night", "Compliance for sleep apnea",
                        "Compliance data"),


        # ============ AK: PAIN & SUFFERING (25 features) ============
        MissingFeature("pain.nociceptor_threshold", "Nociceptor Activation Threshold", MissingSystem.PAIN_SYSTEM,
                        (0, 100), "mN", "Mechanical, thermal, chemical - sensitization",
                        "QST"),
        MissingFeature("pain.a_delta_fiber", "A-Delta Fiber Conduction", MissingSystem.PAIN_SYSTEM,
                        (5, 30), "m/s", "Fast, sharp, well-localized pain",
                        "Nerve study"),
        MissingFeature("pain.c_fiber", "C Fiber Conduction", MissingSystem.PAIN_SYSTEM,
                        (0.5, 2), "m/s", "Slow, dull, poorly localized - burning and aching",
                        "Nerve study"),
        MissingFeature("pain.gate_modulation", "Pain Gate Modulation", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Spinal cord - TENS and rubbing mechanism",
                        "Theory"),
        MissingFeature("pain.descending_inhibition", "Descending Pain Inhibition", MissingSystem.PAIN_SYSTEM,
                        (0, 100), "%", "PAG-RVM pathway - opioid and placebo effect",
                        "Conditioning"),
        MissingFeature("pain.central_sensitization", "Central Sensitization", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Wind-up - chronic pain amplification",
                        "QST"),
        MissingFeature("pain.allodynia", "Allodynia", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Pain from non-painful stimuli - neuropathic feature",
                        "Testing"),
        MissingFeature("pain.hyperalgesia", "Hyperalgesia", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Exaggerated pain response - peripheral and central",
                        "QST"),
        MissingFeature("pain.phantom_limb", "Phantom Limb Pain", MissingSystem.PAIN_SYSTEM,
                        (0, 10), "NRS", "Amputated limb sensation - cortical remapping",
                        "NRS 0-10"),
        MissingFeature("pain.catastrophizing", "Pain Catastrophizing", MissingSystem.PAIN_SYSTEM,
                        (0, 52), "score", "Magnification, rumination, helplessness - outcome predictor",
                        "PCS"),
        MissingFeature("pain.acceptance", "Pain Acceptance", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Reduced struggle - functional improvement despite pain",
                        "PARS"),
        MissingFeature("pain.placebo_response", "Placebo Response Rate", MissingSystem.PAIN_SYSTEM,
                        (0, 100), "%", "30-40% average - context and expectation dependent",
                        "RCT"),
        MissingFeature("pain.nocebo_effect", "Nocebo Effect", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Negative expectation causes harm - informed consent dilemma",
                        "Studies"),
        MissingFeature("pain.opioid_tolerance", "Opioid Tolerance Development", MissingSystem.PAIN_SYSTEM,
                        (0, 100), "%", "Dose escalation - NMDA receptor mechanism",
                        "Clinical"),
        MissingFeature("pain.opioid_hyperalgesia", "Opioid-Induced Hyperalgesia", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Paradoxical pain increase - chronic use complication",
                        "Clinical"),
        MissingFeature("pain.radicular", "Radicular Pain", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Nerve root pain - sciatica",
                        "Clinical"),
        MissingFeature("pain.myofascial", "Myofascial Pain", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Trigger points in muscle fascia",
                        "Palpation"),
        MissingFeature("pain.headache_tension", "Tension Headache", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Muscle contraction - band-like pressure",
                        "Clinical"),
        MissingFeature("pain.cluster_headache", "Cluster Headache", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Severe unilateral - autonomic features",
                        "Clinical"),
        MissingFeature("pain.trigeminal_neuralgia", "Trigeminal Neuralgia", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "Electric shock pain in face - TN",
                        "Clinical"),
        MissingFeature("pain.visceral_hypersensitivity", "Visceral Hypersensitivity", MissingSystem.PAIN_SYSTEM,
                        (0, 1), "scale", "IBS - gut pain sensitization",
                        "Barostat"),
        MissingFeature("pain.endometriosis_pain", "Endometriosis Pain", MissingSystem.PAIN_SYSTEM,
                        (0, 10), "NRS", "Chronic pelvic pain - dysmenorrhea",
                        "NRS"),
        MissingFeature("pain.fibromyalgia", "Fibromyalgia", MissingSystem.PAIN_SYSTEM,
                        (0, 19), "tender points", "Widespread pain index - central sensitization",
                        "ACR criteria"),
        MissingFeature("pain.crp_central", "CRPS Type I/II", MissingSystem.PAIN_SYSTEM,
                        (0, 2), "type", "Complex regional pain - injury or nerve damage",
                        "Budapest criteria"),
        MissingFeature("pain.cancer_pain", "Cancer Pain", MissingSystem.PAIN_SYSTEM,
                        (0, 3), "type", "Somatic, visceral, neuropathic - WHO analgesic ladder",
                        "Clinical"),


        # ============ AL: DEATH & DECOMPOSITION (20 features) ============
        MissingFeature("death.clinical_death", "Clinical Death", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "binary", "Cardiac and respiratory cessation - reversible window",
                        "Medical"),
        MissingFeature("death.brain_death", "Brain Death Criteria", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Irreversible coma, absent reflexes, apnea - legal death",
                        "Testing"),
        MissingFeature("death.biological_death", "Biological Death", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "binary", "Cellular autolysis - irreversible",
                        "Medical"),
        MissingFeature("death.rigor_mortis", "Rigor Mortis Onset", MissingSystem.DEATH_SYSTEM,
                        (2, 6), "hours", "ATP depletion, calcium release - onset",
                        "Forensic"),
        MissingFeature("death.livor_mortis", "Livor Mortis", MissingSystem.DEATH_SYSTEM,
                        (0.5, 12), "hours", "Blood pooling - gravity-dependent, 30 min to fixation",
                        "Forensic"),
        MissingFeature("death.algor_mortis", "Algor Mortis", MissingSystem.DEATH_SYSTEM,
                        (0.5, 24), "hours", "Body cooling - 1.5°F per hour initially",
                        "Forensic"),
        MissingFeature("death.decomposition_stage", "Decomposition Stage", MissingSystem.DEATH_SYSTEM,
                        (0, 5), "stage", "Fresh, bloat, active decay, advanced decay, dry remains",
                        "Forensic"),
        MissingFeature("death.insect_colonization", "Insect Colonization Sequence", MissingSystem.DEATH_SYSTEM,
                        (0, 10), "hours", "Blowflies first, beetles later - forensic entomology",
                        "Forensic"),
        MissingFeature("death.adipocere", "Adipocere Formation", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Saponification - moist, anaerobic environments",
                        "Forensic"),
        MissingFeature("death.mummification", "Mummification", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Desiccation - arid climate preservation",
                        "Forensic"),
        MissingFeature("death.skeletonization", "Skeletonization Time", MissingSystem.DEATH_SYSTEM,
                        (1, 52), "weeks", "Weeks to years - environment dependent",
                        "Forensic"),
        MissingFeature("death.cremation_temperature", "Cremation Temperature", MissingSystem.DEATH_SYSTEM,
                        (760, 1150), "°C", "760-1150°C - bone fragment processing",
                        "Cremation"),
        MissingFeature("death.embalming", "Embalming Efficacy", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Arterial injection - temporary preservation",
                        "Practice"),
        MissingFeature("death.coffin_birth", "Coffin Birth", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "binary", "Postmortem gas expulsion of fetus - rare",
                        "Forensic"),
        MissingFeature("death.nde_report", "Near-Death Experience Report", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Tunnel, light, life review - cultural variation",
                        "Survey"),
        MissingFeature("death.organ_donation", "Organ Donation", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Consent for transplant after death",
                        "Registry"),
        MissingFeature("death.body_donation", "Body Donation", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Anatomical gift - medical education",
                        "Registry"),
        MissingFeature("death.cadaveric_donation", "Cadaveric Donation", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "scale", "Whole body to science",
                        "Registry"),
        MissingFeature("death.coroner_case", "Coroner Case", MissingSystem.DEATH_SYSTEM,
                        (0, 1), "binary", "Reportable death - forensic autopsy",
                        "Legal"),
        MissingFeature("death.certified_cause", "Certified Cause of Death", MissingSystem.DEATH_SYSTEM,
                        (0, 100), "ICD", "Underlying cause - death certificate",
                        "ICD-10"),


        # ============ AM: HERITAGE & ARCHAEOLOGICAL (20 features) ============
        MissingFeature("herit.provenance", "Artifact Provenance", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1), "scale", "Find location and context - looting destroys value",
                        "Excavation"),
        MissingFeature("herit.stratigraphy", "Stratigraphic Layer", MissingSystem.HERITAGE_SYSTEM,
                        (0, 100), "layers", "Deposition sequence - law of superposition",
                        "Excavation"),
        MissingFeature("herit.radiocarbon", "Radiocarbon Dating", MissingSystem.HERITAGE_SYSTEM,
                        (0, 50000), "years BP", "C-14 half-life 5730 years - calibration curve",
                        "AMS"),
        MissingFeature("herit.dendrochronology", "Dendrochronology", MissingSystem.HERITAGE_SYSTEM,
                        (0, 10000), "years", "Tree ring matching - precise to year",
                        "Wood"),
        MissingFeature("herit.thermoluminescence", "Thermoluminescence", MissingSystem.HERITAGE_SYSTEM,
                        (0, 100000), "years", "Last heating event - pottery and fire",
                        "TL"),
        MissingFeature("herit.obsidian_hydration", "Obsidian Hydration", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1000), "µm", "Water absorption layer - volcanic glass dating",
                        "Microscopy"),
        MissingFeature("herit.archaeomagnetism", "Archaeomagnetism", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1), "scale", "Magnetic field alignment - fired clay records",
                        "Magnetometry"),
        MissingFeature("herit.zooarchaeology", "Zooarchaeology", MissingSystem.HERITAGE_SYSTEM,
                        (0, 100), "species", "Animal bone analysis - diet and husbandry",
                        "Analysis"),
        MissingFeature("herit.paleoethnobotany", "Paleoethnobotany", MissingSystem.HERITAGE_SYSTEM,
                        (0, 100), "species", "Plant remains - agriculture and environment",
                        "Analysis"),
        MissingFeature("herit.bioarchaeology", "Bioarchaeology", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1), "scale", "Human remains - health, diet, migration, trauma",
                        "Analysis"),
        MissingFeature("herit.mortuary", "Mortuary Analysis", MissingSystem.HERITAGE_SYSTEM,
                        (0, 10), "type", "Grave goods, position, treatment - social status",
                        "Excavation"),
        MissingFeature("herit.settlement", "Settlement Pattern", MissingSystem.HERITAGE_SYSTEM,
                        (0, 100), "hectares", "Site size, spacing, hierarchy - political organization",
                        "Survey"),
        MissingFeature("herit.trade_route", "Trade Route Evidence", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1000), "km", "Exotic materials - obsidian, amber, silk",
                        "Sourcing"),
        MissingFeature("herit.iconography", "Iconographic Interpretation", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1), "scale", "Symbol meaning - emic vs etic reading",
                        "Analysis"),
        MissingFeature("herit.crm", "Cultural Resource Management", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1), "scale", "Salvage archaeology - development impact",
                        "Compliance"),
        MissingFeature("herit.pottery_assemblage", "Pottery Assemblage", MissingSystem.HERITAGE_SYSTEM,
                        (0, 10000), "sherds", "Ceramic typology - dating and trade",
                        "Analysis"),
        MissingFeature("herit.lithic_industry", "Lithic Industry", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1000), "artifacts", "Stone tool typology - technology",
                        "Analysis"),
        MissingFeature("herit.metal_artifact", "Metal Artifact Analysis", MissingSystem.HERITAGE_SYSTEM,
                        (0, 100), "items", "Bronze, iron, gold - metallurgy",
                        "Analysis"),
        MissingFeature("herit.bioarchaeology_dna", "Ancient DNA", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1), "scale", "Genetic analysis of ancient remains",
                        "Sequencing"),
        MissingFeature("herit.isotope_analysis", "Isotope Analysis", MissingSystem.HERITAGE_SYSTEM,
                        (0, 1), "scale", "Strontium, carbon, nitrogen - diet and migration",
                        "Mass spec"),
    ]
    
    for f in features:
        if hasattr(f, 'feature_id'):
            MISSING_FEATURES[f.feature_id] = f


_register_missing_features()


def get_missing_feature(feature_id: str) -> MissingFeature:
    return MISSING_FEATURES.get(feature_id)


def get_missing_feature_count() -> int:
    return len(MISSING_FEATURES)


def get_all_missing_feature_ids() -> list:
    return list(MISSING_FEATURES.keys())