"""
Memory System — Phase 3
-----------------------
Each agent has a MemoryBank that stores:
  - Short-term memory: last N raw events the agent experienced
  - Long-term memory: significant life moments (hunger crisis, job loss, etc.)
  - Reflection notes: summaries generated by Groq in Phase 5

Design: memory is stored as simple strings for now.
Phase 5 will use Groq to compress and reflect on long-term memories.
"""

from collections import deque
from typing import List, Optional
from dataclasses import dataclass, field


# Events above this importance score are stored in long-term memory
LONG_TERM_THRESHOLD = 7


@dataclass
class MemoryEntry:
    """A single memory record."""
    tick: int
    description: str
    importance: int = 5        # 1 (trivial) to 10 (life-changing)
    emotion: str = "neutral"   # happy, sad, angry, fearful, neutral


class MemoryBank:
    """
    Stores and retrieves an agent's memories.
    Short-term is a rolling window; long-term is curated by importance.
    """

    SHORT_TERM_CAPACITY = 20
    LONG_TERM_CAPACITY  = 50

    def __init__(self, agent_name: str):
        self.agent_name = agent_name
        self._short_term: deque = deque(maxlen=self.SHORT_TERM_CAPACITY)
        self._long_term: List[MemoryEntry] = []
        self.reflection: Optional[str] = None   # Phase 5: Groq summary

    # ─────────────────────────────────────────────────────────
    # Recording
    # ─────────────────────────────────────────────────────────

    def record(self, tick: int, description: str, importance: int = 5, emotion: str = "neutral"):
        """
        Store a new memory.
        Always adds to short-term; promotes to long-term if important enough.
        """
        entry = MemoryEntry(tick=tick, description=description,
                            importance=importance, emotion=emotion)
        self._short_term.append(entry)

        if importance >= LONG_TERM_THRESHOLD:
            if len(self._long_term) >= self.LONG_TERM_CAPACITY:
                # Evict least important long-term memory
                self._long_term.sort(key=lambda m: m.importance)
                self._long_term.pop(0)
            self._long_term.append(entry)

    def record_critical(self, tick: int, description: str, emotion: str = "fearful"):
        """Shortcut for importance=9 events (starvation, job loss, etc.)."""
        self.record(tick, description, importance=9, emotion=emotion)

    def record_positive(self, tick: int, description: str):
        """Shortcut for importance=8 positive events (promotion, friendship)."""
        self.record(tick, description, importance=8, emotion="happy")

    # ─────────────────────────────────────────────────────────
    # Retrieval
    # ─────────────────────────────────────────────────────────

    def recent(self, n: int = 5) -> List[MemoryEntry]:
        """Return last N short-term memories."""
        items = list(self._short_term)
        return items[-n:]

    def significant(self, n: int = 5) -> List[MemoryEntry]:
        """Return N most important long-term memories."""
        return sorted(self._long_term, key=lambda m: m.importance, reverse=True)[:n]

    def build_context_string(self, n_recent: int = 3, n_significant: int = 3) -> str:
        """
        Build a concise text summary of this agent's memory.
        Used as context for Groq prompts in Phase 4/5.
        """
        recent = self.recent(n_recent)
        significant = self.significant(n_significant)

        lines = [f"Agent: {self.agent_name}"]

        if recent:
            lines.append("Recent experiences:")
            for m in recent:
                lines.append(f"  [T{m.tick}] {m.description} (felt: {m.emotion})")

        if significant:
            lines.append("Important life events:")
            for m in significant:
                lines.append(f"  [T{m.tick}] {m.description} (felt: {m.emotion})")

        if self.reflection:
            lines.append(f"Self-reflection: {self.reflection}")

        return "\n".join(lines)

    def generate_reflection(self, groq_client, current_state: dict) -> Optional[str]:
        """
        Phase 5: Consume recent and long-term memories to create a unified world-view
        and determine a life goal.
        Returns the newly formulated goal string, or None if fallback occurred.
        """
        if not groq_client or not groq_client.enabled:
            # Simple fallback reflection
            self.reflection = "I am taking life one day at a time."
            return "survive"

        prompt = f"""
You are the inner voice of '{self.agent_name}'.
Review your memories and form a core reflection about your life and what you should strive for.

Recent memories:
{[m.description for m in self.recent(10)]}
Significant events:
{[m.description for m in self.significant(5)]}

Current State:
{current_state}

What is your overall perspective on life right now? What should your main goal be?
Keep the reflection to 1 short sentence. Keep the goal to 1-3 words.

Respond STRICTLY in JSON format:
{{
  "reflection": "...",
  "goal": "..."
}}
"""
        import json
        from utils.logger import get_logger
        logger = get_logger(__name__)
        
        try:
            response = groq_client.complete(prompt)
            data = json.loads(response)
            self.reflection = data.get("reflection", self.reflection)
            new_goal = data.get("goal")
            logger.info(f"🧠 [Reflection] {self.agent_name} ponders: '{self.reflection}' (New Goal: {new_goal})")
            return new_goal
        except Exception as e:
            logger.debug(f"Failed to generate reflection for {self.agent_name}: {e}")
            return None

    def get_snapshot(self) -> dict:
        return {
            "recent": [
                {"tick": m.tick, "text": m.description, "emotion": m.emotion}
                for m in self.recent(5)
            ],
            "significant": [
                {"tick": m.tick, "text": m.description, "importance": m.importance}
                for m in self.significant(5)
            ],
            "reflection": self.reflection,
        }
